/* ============================================================
   Scripted councils, part 1 — the four questions on the poster.

   Placeholders resolved by the engine:
     {0} {1} {2}  the short names of whoever is in each seat (so a reply
                  to "Naval" becomes a reply to "James" after a Replace)
     {q}          the user's follow-up, verbatim
     {ctx}        context the user added
   ============================================================ */
import type { CouncilScript } from '../types';
import { t, q } from './helpers';

export const DISCIPLINE: CouncilScript = {
  id: 'discipline',
  area: 'other',
  question: 'How can I be more disciplined?',
  title: 'Discipline',
  keywords: ['discipline', 'disciplined', 'self-control', 'willpower', 'procrastinat', 'lazy', 'focus', 'consistent', 'consistency', 'routine', 'motivation', 'motivated', 'stick to', 'follow through', 'habit', 'wake up', 'morning', 'distract'],
  seats: [
    {
      figureId: 'marcus-aurelius',
      why: 'The most-read notes ever written by someone talking himself into getting out of bed. He treats discipline as a duty to your own nature — the view worth hearing first.',
      bookId: 'meditations',
      bookWhy: 'Book V opens with Marcus at dawn, not wanting to rise. Every question about discipline starts in that bed.',
      bestStart: true,
      r1: [t('Discipline is freedom. When you master your mind, you are no longer a slave to your impulses.')],
      r2: [
        t('{1}, leverage is a fine word for a merchant. But the work is the same whether it compounds or not: rise, and do what a human being is for. The morning does not ask about returns.'),
        q('marcus-aurelius', 0),
      ],
      f1: [t('You ask: "{q}". I would answer as I answer myself. Is it in your power? Then do it now, without the commentary. Is it not? Then let it go the way you let go of the weather.')],
      f2: [t('Again, then: "{q}". The obstacle you name is material, not excuse.'), q('marcus-aurelius', 1)],
      ctx: [t('{ctx} — that changes the shape of the duty, not the duty. Ask what a good person does in exactly that position, and do that, without complaint.')],
      direct: [
        [t('You ask me alone: "{q}". Then hear it plainly: at dawn, when you do not want to rise, tell yourself you are rising to the work of a human being. The rest is commentary.')],
        [t('"{q}" — strip the story from it. Look at the thing itself, decide what in it is yours, and act. Another hour of deliberation will not improve you.')],
      ],
      differs: 'Discipline is a duty to your own nature: get up and do the human work, returns or not.',
    },
    {
      figureId: 'naval-ravikant',
      why: 'A living entrepreneur who argues that discipline is wasted when it isn’t attached to judgment and leverage. He will push back on the Stoics.',
      bookId: 'almanack',
      bookWhy: 'His notes on building yourself: discipline as a design problem — habits, environment, identity — rather than a test of will.',
      r1: [t('I agree, but discipline is also about leverage. It’s not just self-control, it’s directing your attention toward what compounds.')],
      r2: [
        t('{0}, the morning does ask, though — because you only get so many of them. Self-control pointed at the wrong thing is just a well-organised waste. Discipline without judgment is a tax; with judgment it’s compounding.'),
        q('naval-ravikant', 1),
      ],
      f1: [t('On "{q}" — I’d look for the smallest repeatable version. Discipline only compounds when the unit is small enough to survive a bad day.')],
      f2: [t('"{q}" — treat it as a design problem. Change the default so the disciplined choice is the lazy one. Willpower is a bad long-term strategy; environment is a good one.')],
      ctx: [t('{ctx} — good, that’s a real constraint, and constraints are where leverage hides. Given that, which single input moves the most output?')],
      direct: [
        [t('Directly: "{q}". Most of that is a judgment problem dressed as a discipline problem. Decide what you’re optimising for; the discipline follows the decision.')],
        [t('"{q}" — don’t build the habit, build the person the habit belongs to. Then the habit is just what that person does on a Tuesday.')],
      ],
      differs: 'Discipline is only worth what it’s pointed at — self-control without judgment is a well-organised waste.',
    },
    {
      figureId: 'simone-de-beauvoir',
      why: 'The existentialist who insisted freedom is made, not given. She will ask whether the discipline you want is yours or someone else’s.',
      bookId: 'second-sex',
      bookWhy: 'The chapter on the independent woman: what a self-directed life costs and requires, for anyone trying to choose their own shape.',
      r1: [t('Discipline should not make you smaller. It’s a tool for a more authentic life — to choose, not to conform.')],
      r2: [
        t('You both speak as if the disciplined self were already known — {0}’s good man, {1}’s compounding self. But one is not born that self; one becomes it, and the becoming is the freedom. A discipline you did not choose is obedience with better posture.'),
        q('simone-de-beauvoir', 0),
      ],
      f1: [t('"{q}" — before you answer it, ask whose question it is. If it comes from a project you chose, the answer will feel like more freedom, not less.')],
      f2: [t('On "{q}": I distrust any answer that requires you to become smaller in order to keep it. Discipline serves a life; a life does not serve discipline.')],
      ctx: [t('{ctx} — a situation is not a sentence. You did not choose all of it. Within it, what can you still make?')],
      direct: [
        [t('Since you ask me: "{q}" — I cannot answer it for you, and that is not evasion; it is the point. Choose, own the choice, and let that be the discipline.')],
        [t('"{q}" — ask whether the answer makes you larger or smaller. That is my only test, and it has never failed me.')],
      ],
      differs: 'Discipline must be chosen, not inherited; otherwise it’s conformity with good posture.',
    },
  ],
  alternates: [
    [
      {
        figureId: 'seneca',
        why: 'The Stoic who wrote about time as the one thing you cannot buy back — a more practical Stoic than Marcus, and a warmer one.',
        bookId: 'letters-stoic',
        bookWhy: 'Letter XIII shows how much resolve is lost to imagined fears. Read it when your discipline keeps dissolving into worry.',
        r1: [t('Discipline is mostly a matter of time. Not that we have too little of it, but that we let it be taken — by fears we never examine and by other people’s errands.'), q('seneca', 1)],
        r2: [t('{1} is right that it must be pointed somewhere. But I would add what {2} circles: most of what stops us is not weakness but dread.'), q('seneca', 0)],
        f1: [t('"{q}" — rehearse the worst case in daylight. What can be looked at directly can be borne.')],
        f2: [t('Again: "{q}". How much of your time is this taking, and would you spend money the way you are spending those hours?')],
        ctx: [t('{ctx} — then treat it as a rehearsal: fortune has handed you a small version of a hard thing so you can practise.')],
        direct: [[t('You ask me alone: "{q}". Write what you fear will happen if you fail, and beside it what you would actually do. The second column is always shorter.')]],
        differs: 'Discipline is guarding your time and rehearsing your fears in daylight, so neither can rob you.',
      },
    ],
    [
      {
        figureId: 'james-clear',
        why: 'The most practical modern writer on habits — replaces leverage with systems, and treats discipline as a design flaw rather than a character flaw.',
        bookId: 'atomic-habits',
        bookWhy: 'Chapter 2 turns discipline into identity: every action is a vote for who you are becoming.',
        r1: [t('I’d take the word “discipline” off the table. It isn’t about wanting it more; it’s about making the wanted thing the easy thing.'), q('james-clear', 0)],
        r2: [t('{0} talks about rising to the work; I’d make the work two minutes long so rising isn’t a battle. And {2} — yes, choose it. But choose it with an action.'), q('james-clear', 1)],
        f1: [t('On "{q}": make it obvious, attractive, easy and satisfying. Which of the four is missing? It’s usually "easy".')],
        f2: [t('"{q}" — shrink it until it takes two minutes, attach it to something you already do, and never miss twice.')],
        ctx: [t('{ctx} — that’s your environment, and environment beats willpower. Change what’s in front of you before you try to change yourself.')],
        direct: [[t('Directly: "{q}". Don’t set a goal; design the default so that the good choice is the lazy one.')]],
        differs: 'Discipline is a system, not a trait — make the good choice obvious, easy and satisfying.',
      },
    ],
    [
      {
        figureId: 'angela-duckworth',
        why: 'The psychologist who measured what discipline actually predicts — a research-grounded voice in place of the existentialist.',
        bookId: 'grit',
        bookWhy: 'Chapter 7 shows what disciplined effort looks like when it improves you rather than merely exhausting you.',
        r1: [t('In the data, discipline that lasts looks less like willpower and more like interest, then practice, then purpose.'), q('angela-duckworth', 0)],
        r2: [t('{0} and {1} both make it sound like a decision. What I saw in the people who endured was a structure: same time, same place, a stretch goal, feedback. Decide once, and let the routine decide after that.')],
        f1: [t('"{q}" — which stage are you in: interest, practice or purpose? Don’t demand purpose from a beginner.')],
        f2: [t('On "{q}": effort counts twice. A small amount of consistent effort beats a burst of talent every time.')],
        ctx: [t('{ctx} — fine; grit isn’t stubbornness. Keep the top-level goal and be ruthless about swapping the lower-level ones that aren’t working.')],
        direct: [[t('You asked me: "{q}". Pick a stretch goal, protect a daily slot for it, get feedback weekly, and don’t judge it for a month.')]],
        differs: 'Endurance beats enthusiasm — build a deliberate-practice loop and let it carry you.',
      },
    ],
  ],
  takeaways: {
    commonGround: 'Discipline isn’t restriction — it’s freedom. It helps you focus on what truly matters, creates leverage for a better future, and allows you to live a more authentic life by making intentional choices.',
    fits: 'If you fight yourself every morning, start with {0}: it’s about identity, not motivation. If you are disciplined but scattered, {1}’s question — what compounds? — matters more. If your routines feel like someone else’s life, {2}’s test applies: does this make you larger?',
    nextStep: 'Tonight, write one sentence: “Tomorrow I rise to ___.” Fill the blank with a single act you chose, not one you inherited. Do it before 9am, then note how it felt.',
  },
};

export const CAREER: CouncilScript = {
  id: 'career',
  area: 'career',
  question: 'What does a meaningful career look like?',
  title: 'a Meaningful Career',
  keywords: ['career', 'job', 'work', 'meaningful', 'meaning', 'purpose', 'calling', 'vocation', 'passion', 'promotion', 'quit', 'boss', 'profession', 'what should i do with my life', 'fulfil', 'fulfill', 'burnout', 'burned out', 'burnt out'],
  seats: [
    {
      figureId: 'viktor-frankl',
      why: 'A psychiatrist who watched what sustained people in the worst place on earth — and concluded it was a task waiting to be done.',
      bookId: 'mans-search',
      bookWhy: 'Settles what “meaning” means before any theory of careers gets hold of the word.',
      r1: [t('Meaning is not something you find in a job description. It is found in three places: in what you create, in whom you love, and in the attitude you take toward what you cannot change. A career is meaningful when it is an answer to what life is asking of you.')],
      r2: [t('{2}, the call is real, but I would turn it around: do not ask what you expect from life — ask what life expects from you. And {1}, skill is not opposed to meaning. A task done well for someone else’s sake is one of the three roads to it.'), q('viktor-frankl', 0)],
      f1: [t('"{q}" — I would answer with a question: who, besides you, would be better off if you did this well? Meaning tends to hide there.')],
      f2: [t('Again: "{q}". Even the worst job carries a stance you are free to take toward it, and the stance is often where the meaning starts.')],
      ctx: [t('{ctx} — then the question is concrete, which is better. What is this situation, specifically, asking of you?')],
      direct: [[t('You ask me alone: "{q}". Look for the task that only you can do, for someone who needs it done. Meaning will not be found by looking for meaning.')]],
      differs: 'Meaning comes from responsibility — a task or a person beyond yourself — not from a feeling about the work.',
    },
    {
      figureId: 'cal-newport',
      why: 'The sceptic of “follow your passion”: skill first, then control, then meaning. He will argue with the mythologist.',
      bookId: 'so-good',
      bookWhy: 'The most actionable of the three — a rule you can apply on Monday morning.',
      bestStart: true,
      r1: [t('I would be careful with the word “meaningful”. It is usually a feeling people have after they have become good at something rare, not before.'), q('cal-newport', 0)],
      r2: [t('{2}, “the call” is where most bad career advice comes from. The people I studied who love their work rarely heard one. They got good, gained control over their work, and then found a mission. The bliss came late, and it was earned.')],
      f1: [t('On "{q}": what rare and valuable skill does it build? If the answer is none, it is a hope, not a plan.')],
      f2: [t('"{q}" — treat the next year as building career capital. Control, mission and, yes, passion are what you buy with it later.')],
      ctx: [t('{ctx} — that is your current career capital. Spend it on autonomy over your work before you spend it on a title.')],
      direct: [[t('Directly: "{q}". Pick the skill, block ninety minutes a day of undistracted practice, and review in ninety days. Feelings later.')]],
      differs: 'Skill first: get rare and valuable, buy control with it, and let passion arrive afterwards.',
    },
    {
      figureId: 'joseph-campbell',
      why: 'The scholar of myth who coined “follow your bliss” — the case for the inner call, made seriously and with its costs attached.',
      bookId: 'power-of-myth',
      bookWhy: 'The counter-argument in full: the case for the call, and what it asks you to give up.',
      r1: [q('joseph-campbell', 0), t('The hero does not start with skills. He starts with the call.')],
      r2: [t('{1}, you describe the return journey and call it the whole story. The refusal of the call is the most common tale I know — a life of getting, very competent, never lived. The cave you fear to enter holds the treasure you seek.')],
      f1: [t('"{q}" — does it make you feel alive, or merely safe? Follow the first and budget for the second.')],
      f2: [t('On "{q}": every threshold has a guardian, usually fear dressed as prudence. Name the guardian and you are halfway across.')],
      ctx: [t('{ctx} — you are describing the belly of the whale: the old self dissolving. It is supposed to feel like this.')],
      direct: [[t('Since you ask me: "{q}" — where is your bliss? Not pleasure; the thing that makes you feel most alive. That is the thread. Hold it.')]],
      differs: 'Start with the inner call and accept the cost; competence without a call is a refused adventure.',
    },
  ],
  alternates: [
    [
      {
        figureId: 'hannah-arendt',
        why: 'The political thinker who split what we do into labour, work and action — and would ask which one your career is.',
        bookId: 'human-condition',
        bookWhy: 'Chapter V asks which kind of “work” you actually mean, and argues the most human kind is done among others.',
        r1: [t('Which kind of work do you mean? Labour keeps you alive and leaves nothing behind. Work makes things that last. Action begins something new among other people. Most careers are labour dressed as work; meaning lives in action.'), q('hannah-arendt', 0)],
        r2: [t('{1} builds skill and {2} follows a call — but both of you speak of a person alone. Nothing new is ever begun alone. Find the people in whose presence you can act; that is where a career becomes a life.')],
        f1: [t('"{q}" — ask which activity you mean: labour, work or action. They need different answers.')],
        f2: [t('On "{q}": the capacity to begin something is the one thing no situation can take from you. Begin, and see who joins.')],
        ctx: [t('{ctx} — a fact of your world; and the world is what lies between us, not inside us. What does it let you begin?')],
        direct: [[t('You ask me: "{q}". Does the role let you begin anything, in front of people who can see you do it? If not, it may be honourable labour, but it is not yet action.')]],
        differs: 'A meaningful career lets you begin things among others — action, not merely labour or craft.',
      },
    ],
    [
      {
        figureId: 'naval-ravikant',
        why: 'An entrepreneur who says meaning is downstream of specific knowledge and leverage — the practical replacement for Newport.',
        bookId: 'almanack',
        bookWhy: 'Part I on specific knowledge is the mechanics behind “find the work that feels like play”.',
        r1: [t('Specific knowledge is found by pursuing your genuine curiosity, not whatever is hot right now. A meaningful career is where what you are best at, what you cannot be trained for, and what the world will pay for line up.'), q('naval-ravikant', 2)],
        r2: [t('{2}, I would call the “call” curiosity, and {0} would call it responsibility — but the practical version is the same: find what feels like play to you and looks like work to others.'), q('naval-ravikant', 1)],
        f1: [t('"{q}" — zoom out. What is the game, who are the long-term people in it, and would you play it for twenty years?')],
        f2: [t('On "{q}": earn with your mind, not your time. If the answer trades hours for money, it will not feel meaningful for long.')],
        ctx: [t('{ctx} — good, a constraint. Constraints are where leverage hides.')],
        direct: [[t('Directly: "{q}". List what you do that feels like play but others find hard. That list is the career.')]],
        differs: 'Find the work that feels like play to you and looks like work to others, then compound it.',
      },
    ],
    [
      {
        figureId: 'rainer-maria-rilke',
        why: 'The poet who told a young man that the only question about a vocation is “must I?” — a quieter voice than the mythologist.',
        bookId: 'letters-young-poet',
        bookWhy: 'Letter One asks the one question a career cannot dodge.',
        r1: [q('rainer-maria-rilke', 0), t('If the answer is a simple, strong yes, build your life around that necessity — even its most trivial hour must be a sign of it.')],
        r2: [t('{1} counsels patience with skill, and I agree — but patience with the question, too.'), q('rainer-maria-rilke', 1), t('A career, like a poem, ripens; it is not decided.')],
        f1: [t('"{q}" — I would not answer it yet. Live with it a while. Some questions are rooms one must live in before they become doors.')],
        f2: [t('On "{q}": would you have to do this even if no one ever noticed? If yes, build your life around that yes.')],
        ctx: [t('{ctx} — then be patient with what is unsolved. Difficulty is often the sign that the path is real.')],
        direct: [[t('You ask me: "{q}". Go into yourself, and in the most silent hour of your night ask whether you must. Everything else follows.')]],
        differs: 'The only test of a vocation is necessity — and necessity is found in solitude, slowly.',
      },
    ],
  ],
  takeaways: {
    commonGround: 'A meaningful career is not a title you find but a relationship you build — between what you can do well, what the world needs from you, and something in you that says yes. All three agree it is earned over years, not discovered in a moment.',
    fits: 'If you are waiting to feel called before committing, {1}’s rule applies: get good first. If you are competent but hollow, {0}’s question — what is being asked of me? — is the missing piece. If you are safe and restless, {2} is describing you.',
    nextStep: 'List three tasks from the last month that absorbed you completely. For each, note who it helped and what skill it used. The overlap is your next move.',
  },
};

export const FAILURE: CouncilScript = {
  id: 'failure',
  area: 'other',
  question: 'How do I handle failure?',
  title: 'Failure',
  keywords: ['failure', 'failed', 'fail', 'failing', 'mistake', 'rejected', 'rejection', 'lost', 'loss', 'setback', 'fired', 'laid off', 'bounce back', 'resilien', 'screwed up', 'messed up', 'embarrass', 'give up', 'gave up', 'recover'],
  seats: [
    {
      figureId: 'seneca',
      why: 'The Stoic who was exiled, ruined and recalled — and wrote the calmest letters we have about what fear does to a mind.',
      bookId: 'letters-stoic',
      bookWhy: 'Short, calm, and about exactly this feeling — the fear of what a failure will lead to.',
      bestStart: true,
      r1: [t('First, separate the failure from what you fear will follow it.'), q('seneca', 0)],
      r2: [t('{2}, fire is a fine image until it is your house. Not every failure is a gift; some are simply losses, and the Stoic answer to a loss is not to call it a gain but to bear it without being ruled by it.')],
      f1: [t('"{q}" — rehearse the worst of it in daylight. What you can look at directly, you can bear.')],
      f2: [t('Again: "{q}". How much of your time is this taking? Would you spend money the way you are spending these hours?')],
      ctx: [t('{ctx} — then treat it as a rehearsal. Fortune has handed you a small version of the hard thing so that you can practise.')],
      direct: [[t('You ask me alone: "{q}". Two columns: what you fear will happen, and what you would actually do if it did. The second is always shorter.')]],
      differs: 'Sort the fear from the fact; most of what follows a failure is imagined, and a real loss is borne, not rebranded.',
    },
    {
      figureId: 'carol-dweck',
      why: 'The psychologist whose research shows a failure is only a verdict if you believe ability is fixed.',
      bookId: 'mindset',
      bookWhy: 'Chapter 2 shows, in people’s own words, what failure feels like in each mindset — the fastest way to recognise which one you are in.',
      r1: [t('Notice the sentence you are saying about yourself. “I failed” is a fact. “I’m a failure” is a fixed-mindset verdict, and it is what makes the next attempt impossible.'), q('carol-dweck', 0)],
      r2: [t('{2}, “be the fire” is a mindset instruction, whether or not you like the word. And {0} — the rehearsal you describe works, but only in a growth frame. Rehearse the worst case as a fixed-mindset person and all you rehearse is your own inadequacy.')],
      f1: [t('On "{q}": add the word “yet”. Then ask what, specifically, to practise.')],
      f2: [t('"{q}" — praise the effort and the strategy, not the outcome. For yourself, too.')],
      ctx: [t('{ctx} — that is a real constraint, not a verdict on you. Keep the two separate.')],
      direct: [[t('You asked me: "{q}". The failure hurts in both mindsets; only in one does it define you. Choose a slightly harder task than is comfortable, and go again.')]],
      differs: 'A failure is information unless you believe ability is fixed — then it is a verdict. Change the belief.',
    },
    {
      figureId: 'nassim-taleb',
      why: 'The risk philosopher who thinks a survivable failure is the best thing that can happen to you — and will say so bluntly.',
      bookId: 'antifragile',
      bookWhy: 'The prologue states the whole idea: a survivable failure is a stressor, and stressors are how things get stronger.',
      r1: [t('You are all being too gentle. A failure that did not kill you is a stressor, and stressors are how anything worth being gets stronger.'), q('nassim-taleb', 0), t('Be the fire.')],
      r2: [t('{1}, mindset is fine, but it is downstream of structure. Set things up so that being wrong costs little and being right pays a lot, and you can afford to fail a hundred times — no attitude required. {0}, agreed: the point is never to fail big. Small failures, often; ruin, never.')],
      f1: [t('"{q}" — wrong question. Ask how to make the next attempt cheap enough to make ten of them.')],
      f2: [t('On "{q}": avoid advice from people who bore no cost for being wrong. Then check whether you are one of them.')],
      ctx: [t('{ctx} — a stressor. Small, frequent ones are how a system learns. Fear their absence more than their presence.')],
      direct: [[t('Directly: "{q}". Remove the fragilities first — debt, dependence on one outcome, commitments you cannot exit. Then failing is affordable.')]],
      differs: 'Design for failure: cap the downside, keep the upside open, and let small failures make you stronger.',
    },
  ],
  alternates: [
    [
      {
        figureId: 'epictetus',
        why: 'The Stoic teacher born a slave — the strictest voice on what is and is not yours.',
        bookId: 'enchiridion',
        bookWhy: 'Ten sections on what is yours and what is not — the shortest possible reset after a failure.',
        r1: [q('epictetus', 0), t('The failure is already outside your control — it happened. Your judgment of it is inside. Work only there.')],
        r2: [t('{1} and {2} both want to make the failure useful. I would first make it small.'), q('epictetus', 1)],
        f1: [t('"{q}" — which part of this is yours? Your judgments, your intentions, your effort. Nothing else.')],
        f2: [t('On "{q}": you are not disturbed by the thing but by your opinion of the thing. Examine the opinion.')],
        ctx: [t('{ctx} — an external. Note it, then return to the only thing fully yours: how you will respond.')],
        direct: [[t('You ask me: "{q}". Decide who you want to be, then do what you have to do. The failure has no vote.')]],
        differs: 'The failure is not yours; your opinion of it is. Correct the opinion.',
      },
    ],
    [
      {
        figureId: 'brene-brown',
        why: 'The researcher on what people who fall and get up actually do — starting with the feeling everyone else skips.',
        bookId: 'rising-strong',
        bookWhy: 'Chapter 4 is the first step: noticing you are hooked before the story about it hardens.',
        r1: [t('Before the lesson, the feeling. Everyone here wants to get to the useful part; the people I studied who rose after a fall sat with the discomfort first.'), q('brene-brown', 0)],
        r2: [t('{0} rehearses the fear and {2} restructures the bet — both are ways of not feeling it. Write the first draft of the story you are telling yourself about this failure, badly, and then look for the parts you made up.')],
        f1: [t('"{q}" — what is the story you are telling yourself about this? Write it down, first draft, badly.')],
        f2: [t('On "{q}": you cannot skip the messy middle. Sit with the discomfort long enough to learn from it.')],
        ctx: [t('{ctx} — thank you for saying that; it is the part most people hide. Name the emotion in it, then get curious instead of armouring up.')],
        direct: [[t('You asked me: "{q}". Finish this sentence honestly: “The story I’m telling myself is…” Then get curious about it.')]],
        differs: 'Reckon with the emotion, rumble with the story, then rewrite the ending — you cannot skip the middle.',
      },
    ],
    [
      {
        figureId: 'ryan-holiday',
        why: 'The modern Stoic who turned Marcus’s hardest line into a method — perception, action, will.',
        bookId: 'obstacle',
        bookWhy: 'Part I on perception: how you see the failure decides what you will do about it.',
        r1: [q('ryan-holiday', 0), t('Not as a slogan — as a sequence. See it clearly, act on the part you can, endure the part you cannot.')],
        r2: [t('{0} covers perception and {1} covers the story; I would add action. The people who came through failures well iterated. They tried the next thing quickly, while the lesson was fresh, before the story about it set.')],
        f1: [t('"{q}" — three disciplines: perception, action, will. Which one is the bottleneck?')],
        f2: [t('On "{q}": this is practice. Every obstacle is a chance to try a virtue on.')],
        ctx: [t('{ctx} — that is the obstacle. Fine. What does it make possible that a smooth road would not?')],
        direct: [[t('You asked me: "{q}". Describe what happened with no adjectives, as if about a stranger. Then do the next right action — not the plan, the action.')]],
        differs: 'Perception, action, will — see it plainly, act fast on what you can, endure the rest.',
      },
    ],
  ],
  takeaways: {
    commonGround: 'All three refuse to let a failure become a story about who you are. {0} strips the dread from it, {1} strips the verdict, {2} strips the fragility — and each insists that the next attempt is the only thing that decides what this one meant.',
    fits: 'If the failure has become a forecast, start with {0}. If it has become a self-description, start with {1}. If it was expensive — money, reputation, health — {2}’s structural question comes first: how do you make the next one affordable?',
    nextStep: 'Write the failure in one plain sentence with no adjectives. Under it, write what it taught you and what it cost. If the cost column is empty, take a slightly bigger swing next time; if it is full, shrink the bet.',
  },
};

export const GOOD_LIFE: CouncilScript = {
  id: 'good-life',
  area: 'other',
  question: 'What is a good life?',
  title: 'the Good Life',
  keywords: ['good life', 'happiness', 'happy', 'meaning of life', 'fulfilling life', 'well-lived', 'well lived', 'content', 'contentment', 'flourish', 'point of', 'purpose of life', 'what matters', 'live well', 'die', 'death', 'regret', 'joy'],
  seats: [
    {
      figureId: 'aristotle',
      why: 'The first thinker to ask the question systematically — and to answer that a good life is an activity, not a feeling.',
      bookId: 'nicomachean-ethics',
      bookWhy: 'The heart of the argument: what a human being is for, and therefore what living well means.',
      r1: [t('Every action aims at some good, and the highest good is the one we want for its own sake: living well — an activity of the soul in accordance with excellence, over a whole life.'), q('aristotle', 0)],
      r2: [t('{1}, the absence of pain is the condition of a good life, not the life. A man asleep is free of disturbance. We are made for activity — for using what is best in us, well, among friends and over time.')],
      f1: [t('"{q}" — ask what it is for. Every action aims at a good; find the good this one aims at, and whether it is for the sake of something higher.')],
      f2: [t('Again: "{q}". We become what we repeatedly do. So the question is about your habits, not your intentions.')],
      ctx: [t('{ctx} — circumstances matter; virtue is the right amount, in the right way, at the right time. What is the mean here?')],
      direct: [[t('You ask me: "{q}". Find the mean between too much and too little, and practise hitting it until it becomes character.')]],
      differs: 'A good life is excellent activity over a whole life — judged at the end, not on a good day.',
    },
    {
      figureId: 'epicurus',
      why: 'The philosopher of the Garden: the good life as friendship, simple needs and the absence of fear. Often slandered, rarely read.',
      bookId: 'art-of-happiness',
      bookWhy: 'The shortest and warmest of the three — one evening, and the whole philosophy in his own words.',
      bestStart: true,
      r1: [t('Simpler than that. A good life is a life without pain in the body and disturbance in the mind — and the surest means to it is friends.'), q('epicurus', 0)],
      r2: [t('{2}, your question is the disturbance I mean. Death is nothing to us; where it is, we are not. Remove the fear of it and “what will come of it all” loses its teeth. What remains is this evening, and who you spend it with.')],
      f1: [t('On "{q}": what pain does it remove, and what disturbance does it add? Weigh those and you have your answer.')],
      f2: [t('"{q}" — be with friends, want little, and fear nothing that cannot hurt you. Most questions fit inside that.')],
      ctx: [t('{ctx} — then look for the tranquil version of the answer, not the grand one. The one you could keep without anxiety.')],
      direct: [[t('You ask me: "{q}". What is the smallest life in which you would be content? Start there, and add only what does not disturb it.')]],
      differs: 'A good life is untroubled: few needs, good friends, no fear of death.',
    },
    {
      figureId: 'leo-tolstoy',
      why: 'The novelist who had everything and hid the rope so he would not hang himself — then found an answer among people who had never read a book.',
      bookId: 'a-confession',
      bookWhy: 'The chapter where a man with everything asks what any of it is for.',
      r1: [t('I had everything the two of you describe — activity, excellence, friends, a garden — and at fifty I found myself asking:'), q('leo-tolstoy', 0), t('Neither of your answers survived that question for me.')],
      r2: [t('{0}, {1} — I do not doubt your answers work for the comfortable. But I found mine not in an argument but in watching people who worked the land and bore their lives with a faith I could not reason my way to. They did not solve the question. They lived it.')],
      f1: [t('"{q}" — I would distrust any answer only the comfortable can afford. How do the people who work with their hands answer it?')],
      f2: [t('On "{q}": is it true at three in the morning, alone? That is the only test I trust.')],
      ctx: [t('{ctx} — I understand. When what I had built stopped meaning anything, the way back was through the plainest things: labour, the people near me, some kind of faith.')],
      direct: [[t('Since you ask me: "{q}" — live so that the question loses its terror. Useful work, love for the people near you, and then see what remains of the doubt.')]],
      differs: 'No theory answers the question; only a life that includes work, love, and some faith that it matters.',
    },
  ],
  alternates: [
    [
      {
        figureId: 'bertrand-russell',
        why: 'The logician who wrote a brisk, practical book on being happy — the empiricist’s reply to Aristotle.',
        bookId: 'conquest-of-happiness',
        bookWhy: 'Chapter 10 is the prescription: widen your interests until brooding has no room.',
        r1: [t('I have met many happy people, and what they had in common was not a theory but an outward-facing life.'), q('bertrand-russell', 0)],
        r2: [t('{2}, your crisis reads to me as a brilliant man thinking about himself. {1} is nearer the mark, though I would replace “want little” with “be interested in much”. The self shrinks to its proper size when there is a great deal else to attend to.')],
        f1: [t('"{q}" — the unhappy are usually thinking about themselves. Widen the circle of your interests until you are too busy to brood.')],
        f2: [t('On "{q}": a great deal of misery comes from wanting the impossible. Check the want before you check the world.')],
        ctx: [t('{ctx} — a real difficulty; but note how much of the suffering is the difficulty and how much is thinking about it at three in the morning.')],
        direct: [[t('You ask me: "{q}". Acquire an impersonal interest and give it an hour a day. Report back in a month.')]],
        differs: 'A good life is outward-facing — wide interests, useful work, affection; the unhappy are usually thinking about themselves.',
      },
    ],
    [
      {
        figureId: 'seneca',
        why: 'The Stoic essay on time — the good life as a life not given away.',
        bookId: 'shortness-of-life',
        bookWhy: 'The opening three chapters make the whole argument in one sitting.',
        r1: [q('seneca', 1), t('The good life is not a matter of length or of pleasure. It is a matter of whether your hours were yours.')],
        r2: [t('{0} wants excellent activity over a whole life and {2} asks what it all comes to — but both assume the life is actually yours to spend. Look at your week. How much of it belongs to other people’s errands and your own dread?')],
        f1: [t('"{q}" — how much of your time is being spent on this, and would you spend money the way you are spending those hours?')],
        f2: [t('On "{q}": rehearse the worst case in daylight. Most of what frightens us shrinks when looked at directly.')],
        ctx: [t('{ctx} — then treat it as a rehearsal: a small version of a hard thing, given so you can practise.')],
        direct: [[t('You ask me: "{q}". Account for a single day as you would for money. Then tell me whether you are rich or poor in it.')]],
        differs: 'A good life is one whose time was actually yours — retire from the crowd and the calendar before you are too old to use it.',
      },
    ],
    [
      {
        figureId: 'marcus-aurelius',
        why: 'The emperor-philosopher writing at night about how to be good tomorrow — a Stoic answer to the novelist’s crisis.',
        bookId: 'meditations',
        bookWhy: 'Book V opens with the dawn passage — the good life at the scale of a single morning.',
        r1: [t('I wrote this to myself, so I will say it to you:'), q('marcus-aurelius', 2), t('A good life is a good day, repeated, until it is over.')],
        r2: [t('{2}’s question — what will come of it all? — I answer with the same thing every night: nothing, and that is freedom. {0} is right that it is an activity. Do the human work today, well, without needing it to be remembered.')],
        f1: [t('You ask: "{q}". Separate what is up to you from what is not, and spend nothing on the second part.')],
        f2: [t('Again: "{q}".'), q('marcus-aurelius', 1)],
        ctx: [t('{ctx} — that changes the shape of the duty, not the duty.')],
        direct: [[t('You ask me: "{q}". Tomorrow, at dawn, rise to the work of a human being. That is the whole of it.')]],
        differs: 'Stop theorising the good life and be a good person today, without needing it to last.',
      },
    ],
  ],
  takeaways: {
    commonGround: 'None of them think a good life is a feeling you can have on a Tuesday. It is a shape a whole life takes — made of friends, of work that uses what is best in you, and of a settled answer to the fear that none of it matters.',
    fits: 'If you are busy and unsure what for, {0}’s question — what is this activity for? — is yours. If you are anxious and overstretched, {1} wants you to want less. If you have the life you planned and it has gone quiet inside, {2} has been where you are.',
    nextStep: 'Write down what a good week would contain — not a good life, a good week. Then check this week against it. The gaps are your answer to the bigger question.',
  },
};
