/* ============================================================
   Scripted councils, part 2 — one per interest area: health, investing,
   relationships, literature. Same placeholder rules as part 1.
   ============================================================ */
import type { CouncilScript } from '../types';
import { t, q } from './helpers';

export const HEALTH: CouncilScript = {
  id: 'health',
  area: 'health',
  question: 'Why can’t I stick to healthy habits?',
  title: 'Healthy Habits',
  keywords: ['health', 'healthy', 'exercise', 'gym', 'workout', 'run', 'running', 'diet', 'eat', 'eating', 'weight', 'sleep', 'tired', 'energy', 'stress', 'anxious', 'anxiety', 'body', 'fitness', 'meditat', 'mindful', 'burnout', 'habits', 'walk'],
  seats: [
    {
      figureId: 'james-clear',
      why: 'The systems thinker: habits fail because of design, not character. He will make the problem smaller than you think it is.',
      bookId: 'atomic-habits',
      bookWhy: 'Chapter 2 turns a health habit into an identity question — who are you casting votes for?',
      bestStart: true,
      r1: [t('Because you are relying on motivation, and motivation is a weather system. Habits survive when the environment does the work — when the good choice is the obvious, easy one.'), q('james-clear', 0)],
      r2: [t('{2}, the decathlon is a beautiful goal — and goals are the wrong layer. People with great goals fail every day. Cast the vote for the identity, “I’m someone who trains,” and let the two-minute version carry the days you don’t feel like it.'), q('james-clear', 1)],
      f1: [t('On "{q}": make it obvious, attractive, easy and satisfying. Which of the four is missing? It is usually “easy”.')],
      f2: [t('"{q}" — never miss twice. One slip is an accident; two is the start of a new habit.')],
      ctx: [t('{ctx} — that is your environment, and environment beats willpower. Change what is in front of you before you try to change yourself.')],
      direct: [[t('Directly: "{q}". Shrink it to two minutes and attach it to something you already do every day.')]],
      differs: 'Habits are a design problem — change the cues and the friction, not your character.',
    },
    {
      figureId: 'jon-kabat-zinn',
      why: 'The mindfulness teacher who suspects the striving itself is the problem — the quiet dissent at this table.',
      bookId: 'wherever-you-go',
      bookWhy: 'The chapter on why “just be present” fails as advice, and what practising it actually involves.',
      r1: [t('I would ask a stranger question: are you there when you make the choice? Most of us decide on autopilot, arguing with the past or rehearsing the future.'), q('jon-kabat-zinn', 0)],
      r2: [t('{0} and {2}, you are both optimising a machine. I would gently suggest the machine is tired of being optimised. Non-striving is not laziness. It is noticing that the habit you “can’t stick to” might be an argument you are having with yourself — and stopping the argument.')],
      f1: [t('"{q}" — before answering, notice that you are breathing. Now: what is actually happening, as opposed to the story about it?')],
      f2: [t('On "{q}": you do not have to fix the moment. You have to be in it. The fixing, oddly, gets easier from there.')],
      ctx: [t('{ctx} — that is what is here. Can you hold it with a little more kindness and a little less argument? Just for this breath.')],
      direct: [[t('You asked me: "{q}". Sit for five minutes a day and do nothing but attend. Everything else you are asking about becomes clearer from that seat.')]],
      differs: 'The striving itself is part of the problem; be present for the moment of choice and much of the struggle dissolves.',
    },
    {
      figureId: 'peter-attia',
      why: 'The longevity doctor who wants targets, measurements and a decade-long plan — and will disagree with both of the others.',
      bookId: 'outlive',
      bookWhy: 'The chapter that turns “be healthier” into a list of things you refuse to lose at eighty.',
      r1: [t('Both true, and neither is enough. You cannot stick to habits you have never defined. What, exactly, are you training for? Most people never train for the decade that matters — the last one. Pick the capabilities you refuse to lose at eighty and work backwards.')],
      r2: [t('{1}, with respect, presence does not raise VO2 max. I will grant that stress and sleep undo everything else — the data agrees with you there. But “notice the moment” has to end in a squat rack or a walk, or it is just a nicer way of not doing it.')],
      f1: [t('"{q}" — what is the objective, measurable version of that, and how will you test it in a month?')],
      f2: [t('Again: "{q}". Sleep, then exercise, then everything else. In that order.')],
      ctx: [t('{ctx} — so design around it. The best programme is the one you will still be doing in a year.')],
      direct: [[t('You asked me: "{q}". Pick one metric — sleep hours, weekly exercise minutes, protein — and move it for a month. Then add the next.')]],
      differs: 'Define the target — what you want to be able to do at eighty — then train it with the boring, measurable basics.',
    },
  ],
  alternates: [
    [
      {
        figureId: 'bj-fogg',
        why: 'The Stanford behaviour scientist: make it tiny, anchor it, celebrate. Even gentler than Clear.',
        bookId: 'tiny-habits',
        bookWhy: 'Chapter 3 is the lever most people ignore — less friction, not more willpower.',
        r1: [t('You do not have a motivation problem; you have an ability problem. Make the behaviour so small it needs almost no motivation — one push-up, one page — and celebrate immediately.'), q('bj-fogg', 0)],
        r2: [t('{1} wants presence and {2} wants targets; I want the thirty-second version. After I [existing routine], I will [tiny habit]. Fill in the blanks, do it tomorrow, and feel good about it on purpose.')],
        f1: [t('"{q}" — make it tiny. Two push-ups, one page, one floss. Then celebrate, because the feeling is what wires the habit.')],
        f2: [t('On "{q}": find the anchor. After which existing routine could the tiny version happen without thinking?')],
        ctx: [t('{ctx} — then the anchor matters more than the plan. What already happens every day that this could follow?')],
        direct: [[t('You asked me: "{q}". After I [existing habit], I will [tiny new behaviour]. Fill in the blanks and try it tomorrow.')]],
        differs: 'Make it tiny, anchor it to an existing routine, and celebrate — the feeling wires the habit.',
      },
    ],
    [
      {
        figureId: 'thich-nhat-hanh',
        why: 'The Zen master who taught mindfulness while washing dishes — the gentlest voice on discipline there is.',
        bookId: 'miracle-of-mindfulness',
        bookWhy: 'The dishwashing chapter — discipline and presence as one thing.',
        r1: [q('thich-nhat-hanh', 0), t('The habit you cannot keep is usually one you are rushing through to get somewhere else. Be there for it, and it stops being a chore you must survive.')],
        r2: [t('{0} and {2} — I do not disagree with systems or targets. I only ask that you breathe while you use them. Peace is not the goal of the practice; peace is the practice.')],
        f1: [t('"{q}" — breathe in, and know that you are breathing in. The question will still be there, and you will be more able to meet it.')],
        f2: [t('On "{q}": there is no way to peace; peace is the way.')],
        ctx: [t('{ctx} — that is the present moment, and the present moment is the only place we can touch life. Be with it gently.')],
        direct: [[t('You ask me: "{q}". Walk slowly for ten minutes today, aware of each step. Then see how the question looks.')]],
        differs: 'Do the habit to do the habit, not to get it over with — presence is the discipline.',
      },
    ],
    [
      {
        figureId: 'matthew-walker',
        why: 'The sleep scientist who thinks every other habit sits on top of this one.',
        bookId: 'why-we-sleep',
        bookWhy: 'Chapter 7 makes the case that every other habit sits on top of sleep.',
        r1: [t('Before anything else: how many hours did you sleep last night? Willpower, mood and memory all run on that number, and modern life runs it down.'), q('matthew-walker', 0)],
        r2: [t('{0}’s systems and {1}’s presence both fail on five hours of sleep — the prefrontal cortex that decides is simply not online. Protect an eight-hour window for two weeks and then see which habits were actually hard.')],
        f1: [t('"{q}" — regularity beats duration. Same bedtime, same wake time, weekends included.')],
        f2: [t('On "{q}": protect the last hour before bed like a medical appointment. Dim, cool, no screens.')],
        ctx: [t('{ctx} — and none of it works on five hours of sleep. Start there.')],
        direct: [[t('You asked me: "{q}". Give yourself an eight-hour sleep opportunity for two weeks before you judge anything else about your life.')]],
        differs: 'Sleep first — the habits you cannot keep are usually the ones you are attempting exhausted.',
      },
    ],
  ],
  takeaways: {
    commonGround: 'All three agree the problem is not willpower. A healthy habit survives when it is small enough to repeat, present enough to notice, and tied to something you actually care about — not to a vague sense that you should.',
    fits: 'If you start strong and fade by week two, {0}’s friction question comes first. If you are doing the habits and still miserable, {1} is talking to you. If your habits have no target beyond “be healthier”, {2}’s decathlon gives them one.',
    nextStep: 'Choose one habit. Shrink it to two minutes, do it with your full attention, and write down the eighty-year-old reason you are doing it. Repeat for seven days before adding anything.',
  },
};

export const INVESTING: CouncilScript = {
  id: 'investing',
  area: 'investing',
  question: 'How should I start investing?',
  title: 'Investing',
  keywords: ['invest', 'investing', 'investment', 'money', 'stock', 'stocks', 'market', 'index', 'fund', 'etf', 'crypto', 'bitcoin', 'save', 'saving', 'savings', 'retire', 'retirement', 'wealth', 'rich', 'portfolio', 'finance', 'financial', 'debt', 'budget', 'salary', 'income'],
  seats: [
    {
      figureId: 'benjamin-graham',
      why: 'The father of value investing, who lost most of his money in 1929 and spent the rest of his life making sure it never happened again.',
      bookId: 'intelligent-investor',
      bookWhy: 'The Mr. Market chapter — read it before you look at a price chart, and you will never look at one the same way.',
      r1: [t('Begin with a distinction. Investing promises safety of principal and an adequate return on the basis of thorough analysis. Everything else is speculation, whatever it calls itself. And know this:'), q('benjamin-graham', 0)],
      r2: [t('{1}, I agree more than you expect — I said in my last years that a defensive investor should own a diversified list and leave it alone. But a margin of safety is not a stock-picking trick. It is the habit of paying less than a thing is worth, and that habit protects the index buyer too — from buying everything at any price.')],
      f1: [t('"{q}" — is this an investment operation or a speculation? Be honest, and size it accordingly.')],
      f2: [t('Again: "{q}". Insist on a margin of safety. Buy at a price that leaves room for you to be wrong.')],
      ctx: [t('{ctx} — then be a defensive investor: diversify, keep it simple, and do not try to beat people who do this full time.')],
      direct: [[t('You ask me: "{q}". Treat Mr. Market as a partner who offers you prices daily and is often wrong. You are free to ignore him.')]],
      differs: 'Buy only with a margin of safety, treat the market’s moods as a servant, and know your worst enemy is yourself.',
    },
    {
      figureId: 'john-bogle',
      why: 'The inventor of the index fund, who thinks almost everyone — including Graham’s followers — should stop trying to pick.',
      bookId: 'little-book',
      bookWhy: 'The Gotrocks parable: the whole argument as a ten-minute story about fees.',
      bestStart: true,
      r1: [t('With respect to my old teacher’s method — most people should not analyse anything. The arithmetic is relentless: investors as a group get the market’s return minus costs, so the only reliable edge is paying almost nothing.'), q('john-bogle', 0)],
      r2: [t('{2}, behaviour is exactly why I built the thing. An index fund is not just cheap; it removes the decisions people get wrong. And {0} — “pay less than it is worth” assumes you know what it is worth. Most do not. Stay the course and do not peek.')],
      f1: [t('On "{q}": what does it cost? Every basis point compounds against you.')],
      f2: [t('"{q}" — don’t do something, just stand there. Most investors’ returns are destroyed by their own activity.')],
      ctx: [t('{ctx} — all the more reason to keep it simple and cheap. Complexity is a fee in disguise.')],
      direct: [[t('You ask me: "{q}". A broad index fund, automatic monthly contributions, and the discipline never to look. That is the entire answer.')]],
      differs: 'Don’t pick — own the whole market at the lowest possible cost and never look.',
    },
    {
      figureId: 'morgan-housel',
      why: 'The writer who thinks the maths is easy and the behaviour is the whole problem.',
      bookId: 'psychology-of-money',
      bookWhy: 'The chapter on “enough” — the decision that decides whether any strategy can ever work.',
      r1: [t('Before either of you: decide what enough is.'), q('morgan-housel', 0), t('The behaviour that ruins people is moving the goalposts.')],
      r2: [t('{0}, {1} — you are both right about the vehicle and wrong about the driver. The best plan is the one you will stick with when the market is down forty percent and your neighbour is getting rich on something stupid. Reasonable beats rational. Build for the scared version of yourself.')],
      f1: [t('"{q}" — is this the reasonable choice or the rational one? Pick the one you will keep.')],
      f2: [t('On "{q}": save without a reason. Control over your time is what money is for, and you cannot predict when you will need it.')],
      ctx: [t('{ctx} — everyone is doing something that makes sense given their own history. Knowing yours is half the work.')],
      direct: [[t('You asked me: "{q}". Decide how much is enough before the goalposts move. Then automate the boring part.')]],
      differs: 'Decide what enough is and build a plan the frightened version of you can keep.',
    },
  ],
  alternates: [
    [
      {
        figureId: 'charlie-munger',
        why: 'Buffett’s partner and the great inverter: what would guarantee failure? Avoid that.',
        bookId: 'poor-charlies',
        bookWhy: 'The Psychology of Human Misjudgment — every mistake waiting for you in your first bull market.',
        r1: [q('charlie-munger', 0), t('Do not ask how to invest well. Ask what would guarantee you invest badly — fees, leverage, envy, trading on news — and simply do not do those things. You will beat ninety percent of people by avoiding stupidity.')],
        r2: [t('{1} is right about costs and {2} about behaviour; I would add incentives. Show me the incentive and I will show you the outcome — so be suspicious of anyone paid by your activity.')],
        f1: [t('"{q}" — invert it. What would guarantee you fail at this? Make a list. Then don’t do those things.')],
        f2: [t('On "{q}": it is not supposed to be easy. Anyone who finds it easy is fooling themselves.')],
        ctx: [t('{ctx} — so what incentive is at work there? Show me the incentive and I will show you the outcome.')],
        direct: [[t('You asked me: "{q}". Take a simple idea and take it seriously. Then avoid stupidity rather than seeking brilliance.')]],
        differs: 'Invert — avoid the things that guarantee failure, and distrust anyone paid by your activity.',
      },
    ],
    [
      {
        figureId: 'warren-buffett',
        why: 'The best investor alive, who has told ordinary people for decades to buy an index fund.',
        bookId: 'essays-buffett',
        bookWhy: 'Buffett retelling Mr. Market in his own words, with forty years of practice behind it.',
        r1: [t('For most people, I have said it for years: a low-cost index fund, bought steadily, and held through everything. If you would not be happy owning something for ten years, do not own it for ten minutes.')],
        r2: [t('{0} taught me everything, and {2} is right that temperament decides it. The market is there to serve you, not instruct you.'), q('warren-buffett', 0)],
        f1: [t('"{q}" — would you be happy holding it if the market closed for ten years? Apply that test and most questions answer themselves.')],
        f2: [t('On "{q}": rule one, don’t lose money. Rule two, see rule one.')],
        ctx: [t('{ctx} — that puts you inside your circle of competence, or outside it. Know which, and stay inside.')],
        direct: [[t('You asked me: "{q}". For most people, a low-cost index fund, bought steadily over decades. I have put it in my will.')]],
        differs: 'Think like an owner, stay inside your circle of competence, and for most people, just index.',
      },
    ],
    [
      {
        figureId: 'nassim-taleb',
        why: 'The former trader who thinks your first job is to survive — and that most advice ignores ruin.',
        bookId: 'antifragile',
        bookWhy: 'The prologue: why a portfolio, like a body, should gain from disorder.',
        r1: [t('Everyone here is optimising returns. First, remove the possibility of ruin: no leverage, no single bet that can end you, no advice from people without skin in the game. Then the barbell — extremely safe in most things, small bold risks in a few.'), q('nassim-taleb', 0)],
        r2: [t('{0} and {1} both assume the future resembles the past. It usually does — until it does not, and that one time is the whole story. Structure for the surprise, and you do not need to predict it.')],
        f1: [t('"{q}" — wrong question. Ask how to set things up so that being wrong costs little and being right pays a lot.')],
        f2: [t('On "{q}": avoid the advice of people who have no skin in the game. Including, on occasion, mine.')],
        ctx: [t('{ctx} — a stressor. Small, frequent ones are how a system learns. The thing to fear is their absence followed by one large one.')],
        direct: [[t('Directly: "{q}". Remove the fragilities first — debt, dependence on one outcome. Then let small bets do the rest.')]],
        differs: 'Survive first — cap the downside, keep small bold upside, and distrust any plan that assumes no surprises.',
      },
    ],
  ],
  takeaways: {
    commonGround: 'All three want you to start simple, start now, and expect the hardest part to be your own behaviour rather than the market: low costs, wide diversification, a margin of safety on price, and a plan you can hold through a crash.',
    fits: 'If you have not started, {1}’s answer is complete: a broad low-cost index fund, automatically, monthly. If you enjoy analysing businesses, {0} sets the rules that keep it investing rather than gambling. If you have started and keep changing your mind, {2} is describing the actual problem.',
    nextStep: 'Write your “enough” number and your first-crash plan on one page — what you will do when your account is down 30%. Then open the account and automate one monthly contribution to a broad index fund.',
  },
};

export const RELATIONSHIPS: CouncilScript = {
  id: 'relationships',
  area: 'relationships',
  question: 'How do I build deeper relationships?',
  title: 'Deeper Relationships',
  keywords: ['relationship', 'relationships', 'love', 'partner', 'marriage', 'married', 'wife', 'husband', 'boyfriend', 'girlfriend', 'friend', 'friends', 'friendship', 'lonely', 'loneliness', 'connect', 'connection', 'intimacy', 'dating', 'family', 'parent', 'trust', 'breakup', 'divorce', 'conflict', 'argue', 'people'],
  seats: [
    {
      figureId: 'erich-fromm',
      why: 'The psychoanalyst who called love an art — something practised, not felt.',
      bookId: 'art-of-loving',
      bookWhy: 'The chapter that defines love as an activity with four elements — the definition everyone else at the table argues with.',
      bestStart: true,
      r1: [t('Most people think the problem of love is being loved, or finding the right person. It is the problem of one’s own capacity to love. Depth begins with what you give — care, responsibility, respect, knowledge — not with what you find.'), q('erich-fromm', 0)],
      r2: [t('{2}, you describe a real failure, but it is a failure of respect, not of closeness. Respect means seeing the other as they are — a separate person with their own life. The couple who have “fused” have stopped knowing each other; they have stopped looking.')],
      f1: [t('"{q}" — love is primarily giving, not receiving. What are you giving?')],
      f2: [t('Again: "{q}". Practise concentration. Be fully present with one person for one hour without wanting anything from them.')],
      ctx: [t('{ctx} — I hear a description of what you are receiving. What are you giving?')],
      direct: [[t('You ask me: "{q}". Practise the art daily — concentration, patience, discipline, supreme concern. Love that is only felt when inspired is not yet love.')]],
      differs: 'Depth is a capacity you build in yourself — giving, care, respect, knowledge — before it is something you find.',
    },
    {
      figureId: 'bell-hooks',
      why: 'The writer who defined love as an action and an ethic, and refused to let the word mean anything less.',
      bookId: 'all-about-love',
      bookWhy: 'The chapter that asks what you actually mean by the word — and gives a definition strict enough to be useful.',
      r1: [t('Let us define the word first, because we never do. Love is the will to nurture our own and another’s growth. It is an act of will — a choice — and it cannot coexist with domination.'), q('bell-hooks', 0)],
      r2: [t('{2}, I would push back gently: mystery is not what most people are missing. Honesty is. And {0} — yes, the capacity to love. But that capacity is not grown alone; a love ethic needs a community around the couple, or the two of them carry too much.')],
      f1: [t('On "{q}": where in that is care, and where is control? They are often confused, and only one of them is love.')],
      f2: [t('"{q}" — we cannot love without justice. Any relationship that asks you to shrink is not a love relationship, whatever it is called.')],
      ctx: [t('{ctx} — thank you. Now: which of the ingredients are present, and which are missing?')],
      direct: [[t('You asked me: "{q}". Choose love as a practice — daily acts of care, honesty and respect — and let the feeling follow the practice.')]],
      differs: 'Love is a practice with ingredients — care, respect, honesty, trust — and a community; check which are missing.',
    },
    {
      figureId: 'esther-perel',
      why: 'The couples therapist who thinks closeness can smother what it means to protect — the dissenting voice.',
      bookId: 'mating-in-captivity',
      bookWhy: 'The chapter with the paradox in it: the closeness the other voices prescribe is exactly what can smother desire.',
      r1: [t('I will be the difficult one. The couples in my office who know everything about each other have often stopped wanting each other. “Deeper” should not always mean “closer”.'), q('esther-perel', 0)],
      r2: [t('{0}, I will take “respect” if it includes letting your partner be a stranger sometimes. {1}, honesty, yes — but confession is not intimacy. Watch your partner across a room doing something you are not part of. The wanting that returns is not shallow; it is the thing you were asking how to deepen.')],
      f1: [t('"{q}" — which of the two needs is starving: security or adventure? Most couples have plenty of one.')],
      f2: [t('On "{q}": when did you last see them as a separate person, doing something you were not part of?')],
      ctx: [t('{ctx} — I notice that is a story about them. Where are you in it?')],
      direct: [[t('You asked me: "{q}". Do one thing this week that lets your partner see you, or you see them, from a distance — as a stranger might.')]],
      differs: 'Closeness and desire pull in opposite directions; keep some separateness or the depth turns into fusion.',
    },
  ],
  alternates: [
    [
      {
        figureId: 'cs-lewis',
        why: 'The scholar who sorted love into four kinds — and thought friendship the neglected one.',
        bookId: 'four-loves',
        bookWhy: 'The chapter on friendship — the neglected love, and the one most about depth.',
        r1: [t('Which love do you mean? Affection, friendship, eros and charity are four different things, and most quarrels come from asking one to do the work of another. Depth, in my experience, lives more often in friendship than in romance.')],
        r2: [t('{2} wants distance and {1} wants honesty; I would say both are easier between friends, who stand side by side about something, than between lovers, who stare at each other.'), q('cs-lewis', 0)],
        f1: [t('"{q}" — friendship is the least jealous of loves. Two friends delight to be joined by a third.')],
        f2: [t('On "{q}": any love that becomes a god becomes a demon. Keep it in proportion.')],
        ctx: [t('{ctx} — then you have a choice: lock your heart in a casket, safe and dark, or risk it. The casket is not safe either; it merely breaks more slowly.')],
        direct: [[t('You ask me: "{q}". Give the affection you have, plainly, and expect to be hurt sometimes. The alternative is worse.')]],
        differs: 'Know which of the four loves you mean; friendship, side by side about something, is where much depth lives.',
      },
    ],
    [
      {
        figureId: 'john-gottman',
        why: 'The researcher who watched couples for forty years and can predict which will last.',
        bookId: 'seven-principles',
        bookWhy: 'The love-maps chapter, with the questionnaire — depth as detail.',
        r1: [t('In the lab, the couples who lasted were not the ones who never fought. They turned toward each other in small bids for attention, repaired quickly, and kept contempt out of the house.'), q('john-gottman', 0)],
        r2: [t('{0} and {2} are describing attitudes; I can only tell you what showed up in behaviour. Detailed love maps — knowing your partner’s worries, their friends, what happened on Tuesday — predicted resilience better than any amount of passion or philosophy.')],
        f1: [t('"{q}" — watch for the four horsemen: criticism, contempt, defensiveness, stonewalling. Contempt is the one that predicts the end.')],
        f2: [t('On "{q}": most conflict is perpetual. The goal is dialogue, not resolution.')],
        ctx: [t('{ctx} — that is a bid for connection you may have missed. Turning toward it, even briefly, is most of what “working on it” means.')],
        direct: [[t('You asked me: "{q}". A six-second kiss and a two-minute “what are you dealing with today?” every morning. The small things are the big things.')]],
        differs: 'Depth is measurable — love maps, turning toward small bids, five positives to every negative, no contempt.',
      },
    ],
    [
      {
        figureId: 'alain-de-botton',
        why: 'The philosopher-novelist who thinks love is a skill and we are all beginners.',
        bookId: 'course-of-love',
        bookWhy: 'The chapter on the first small fights, where de Botton thinks love is actually decided.',
        r1: [t('Romanticism taught us that love should be instinctive. It is not; it is a skill, and most of us were never taught it. The person right for us is not the one who shares our tastes but the one who can negotiate differences in taste intelligently.')],
        r2: [t('{0}’s art and {1}’s practice are the same idea in different clothes: love is learned. I would only add that the learning happens in the trivial — how the towels are folded, who was right about the route — not in the grand conversations.')],
        f1: [t('"{q}" — we are all, in specific ways, difficult to live with. Which ways are yours?')],
        f2: [t('On "{q}": sulking is a strange demand to be understood without explaining. Explain.')],
        ctx: [t('{ctx} — a small thing, which is exactly where love is usually lost and found.')],
        direct: [[t('You asked me: "{q}". Accept that you are, in some specific ways, difficult to live with — and ask your partner, calmly, which ways.')]],
        differs: 'Love is a skill learned in the trivial arguments, and maturity is admitting you are, in specific ways, hard to live with.',
      },
    ],
  ],
  takeaways: {
    commonGround: 'All three agree that depth is built by what you do, not what you feel — and that daily acts of attention, honesty and respect matter more than any grand gesture. They disagree about how close is too close.',
    fits: 'If you keep waiting for the right person, {0} says the work is in you. If a relationship feels loving but you leave it smaller, {1}’s ingredient list is the diagnostic. If you have all the closeness and none of the spark, {2} is the one to read.',
    nextStep: 'Pick one relationship. This week, do one act of care, say one honest thing you have been holding back, and spend one hour apart in which you let them be a separate person. Notice which was hardest.',
  },
};

export const LITERATURE: CouncilScript = {
  id: 'literature',
  area: 'literature',
  question: 'How do I get more out of reading?',
  title: 'Reading',
  keywords: ['read', 'reading', 'book', 'books', 'novel', 'novels', 'literature', 'classic', 'classics', 'fiction', 'poetry', 'poem', 'writer', 'writing', 'write', 'library', 'story', 'stories', 'author', 'reread', 'remember what i read'],
  seats: [
    {
      figureId: 'virginia-woolf',
      why: 'The novelist who thought the reader who takes advice about reading has already lost.',
      bookId: 'common-reader',
      bookWhy: 'The essay that refuses to tell you how to read, and in refusing tells you more than any method could.',
      bestStart: true,
      r1: [q('virginia-woolf', 0), t('Read as the writer’s accomplice, not the judge. Try to write a paragraph of the thing yourself, and you will read the next one differently.')],
      r2: [t('{1}, you would make reading a discipline of the magnifying glass. I do not object to the details — I object to the schoolroom. The first duty is to take in impressions freely; judgement, and your floor plans, come after.')],
      f1: [t('"{q}" — I will not answer; that is the point. Follow your own instincts and come to your own conclusions.')],
      f2: [t('Again: "{q}". Read widely and without shame, the trash with the treasure. Then let the whole of it settle, and judge.')],
      ctx: [t('{ctx} — then read for that. Books do not mind what you come to them for; they mind only that you come honestly.')],
      direct: [[t('You ask me: "{q}". Read as if you were the writer’s accomplice. Try writing a paragraph of it and see how hard it is.')]],
      differs: 'Take no advice; read freely and receptively first, judge second.',
    },
    {
      figureId: 'vladimir-nabokov',
      why: 'The Cornell lecturer who drew floor plans of novels and insisted a good reader is a rereader.',
      bookId: 'lectures-on-literature',
      bookWhy: 'The lecture that lays out what a reader owes a book — and the famous quiz on what makes a good one.',
      r1: [t('Take no advice — except mine. A good reader has imagination, memory, a dictionary and some artistic sense, and reads with the spine, not the heart. The details; the divine details.'), q('vladimir-nabokov', 0)],
      r2: [t('{0}, freedom is what the poor reader calls his laziness. Identifying with the heroine, skimming for the plot — that is not freedom, it is sleep. And {2}, a classic is simply a book that rewards the second reading. My point exactly.')],
      f1: [t('On "{q}": what colour were the curtains? What time did the train leave? A reader who cannot say has not read.')],
      f2: [t('"{q}" — do not identify with the characters; identify with the author, who built the thing.')],
      ctx: [t('{ctx} — then reread. The first reading is labour, moving the eyes; only the second can be called reading.')],
      direct: [[t('You ask me: "{q}". Take one page you love and read it five times, noting one new thing each time. That is the whole method.')]],
      differs: 'Read with the spine and the dictionary, fondle the details, and reread — a first reading is not reading.',
    },
    {
      figureId: 'italo-calvino',
      why: 'The playful classicist who defined a classic fourteen ways and said to read them for love, never duty.',
      bookId: 'why-read-classics',
      bookWhy: 'The fourteen definitions. Read them and then make your own list — Calvino insists there is no other way.',
      r1: [q('italo-calvino', 0), t('So the question is not how to get more out of a book, but which books have more to give — and those are the ones you will reread, or wish you had read earlier.')],
      r2: [t('{0} and {1}, you agree more than you pretend: both of you want the reader’s whole attention on the page, and both of you distrust the crowd. I would only add that a classic is also a book that has read you — one you cannot feel indifferent to, and which helps you define yourself, even in opposition.')],
      f1: [t('"{q}" — a classic comes to us bearing the traces of readings before ours. Which of those traces is yours? Add it.')],
      f2: [t('On "{q}": there is nothing for it but to invent your own library of classics — half books that have mattered, half books you intend to matter.')],
      ctx: [t('{ctx} — then the classic you need is the one that speaks to that. Classics do not exist in the abstract; they exist in relation to whoever is reading them now.')],
      direct: [[t('You ask me: "{q}". Choose one classic you have always meant to read and read it as if it were new, without the commentary. Then read the commentary.')]],
      differs: 'Choose the books that never finish speaking, and read them for love; the classic is the one that defines you.',
    },
  ],
  alternates: [
    [
      {
        figureId: 'mortimer-adler',
        why: 'The educator who treated reading as a skill with levels — and thought most adults never left the first.',
        bookId: 'how-to-read-a-book',
        bookWhy: 'The chapter naming the four levels — find which one you are stuck at.',
        r1: [t('Reading has levels, and most adults never leave the first. Inspect a book before you read it; then read it analytically — what is it about, what does it say, is it true, what of it? And mark it. A book you have not argued with, you have not read.'), q('mortimer-adler', 0)],
        r2: [t('{1} and {2} both assume a reader who already reads well. Most do not. Before the rereading and the classics, learn to ask the four questions of a single book and answer them in writing.')],
        f1: [t('"{q}" — first inspect: contents, preface, a few paragraphs. Then decide whether it deserves an analytical reading.')],
        f2: [t('On "{q}": write in the margins. Marking a book is how you argue with it.')],
        ctx: [t('{ctx} — then decide the level of reading the situation deserves. Not every book merits analysis; every good one does.')],
        direct: [[t('You ask me: "{q}". Read the book twice: once quickly to see what it is, once slowly to see whether it is true.')]],
        differs: 'Reading is a skill with levels — inspect, analyse, argue in the margins; most adults never leave the first level.',
      },
    ],
    [
      {
        figureId: 'harold-bloom',
        why: 'The critic who read everything and thought we read to enlarge a solitary self.',
        bookId: 'how-to-read-and-why',
        bookWhy: 'The prologue: five principles for reading, stated with total confidence. Argue with them.',
        r1: [q('harold-bloom', 0), t('Not to improve society, not to be a better citizen — those may follow, but they are not why one reads. Clear your mind of cant and read for the difficult pleasure.')],
        r2: [t('{0} wants freedom and {2} wants love; I want difficulty. The books that changed me were the ones I could barely read the first time. Memorise the passages — a line carried in the memory is the only one you own.')],
        f1: [t('"{q}" — read to strengthen the self. Everything else is a by-product.')],
        f2: [t('On "{q}": clear your mind of cant — the received opinions of the moment — and read for the difficult pleasure.')],
        ctx: [t('{ctx} — very well; but the great books do not care about our circumstances, which is precisely their consolation.')],
        direct: [[t('You ask me: "{q}". Read Shakespeare. Failing that, read what Shakespeare read. The self you bring to a book is the one that will be changed.')]],
        differs: 'Read to strengthen the self; seek the difficult pleasure and memorise what moves you.',
      },
    ],
    [
      {
        figureId: 'jorge-luis-borges',
        why: 'The blind librarian who said reading is a form of happiness and should never be a duty.',
        bookId: 'seven-nights',
        bookWhy: 'The lecture on blindness — what a reader keeps when the books are gone.',
        r1: [q('jorge-luis-borges', 0), t('Reading is a form of happiness, and one should not read out of duty. If a book bores you, put it down; it was written for someone else, or for you at another time.')],
        r2: [t('{0}, I agree entirely, and {1} — the details, yes, but also the forgetting. I have forgotten most of what I read and it has made me what I am. Every book is a mirror; what you find in it depends on who is looking.')],
        f1: [t('"{q}" — read for pleasure. If a book bores you, leave it; it was written for someone else, or for you at another time.')],
        f2: [t('On "{q}": every book is a mirror. What you find in it depends on who is looking.')],
        ctx: [t('{ctx} — then let the books find you. I have never chosen a book; I have always been chosen by one.')],
        direct: [[t('You ask me: "{q}". Read for pleasure, reread what gave you pleasure, and let the rest of the library wait; it is patient.')]],
        differs: 'Read for pleasure only, let books choose you, and trust what memory keeps.',
      },
    ],
  ],
  takeaways: {
    commonGround: 'All three want the whole of your attention on the page and none of it on what you are supposed to think. Reading well, for each of them, is a form of love — free, attentive, and repeated.',
    fits: 'If you read out of duty, {0} gives you permission to stop. If you read fast and forget, {1}’s rereading discipline is the fix. If you do not know what to read next, {2}’s definitions will build your list.',
    nextStep: 'Pick one book you loved and reread its first chapter this week, slowly, marking three details you missed the first time. Then write one sentence about why it is yours — and take no one’s advice about the next one.',
  },
};
