/* ============================================================
   Books, part 1: the philosophy / career / failure / good-life shelves.
   `text` is either public-domain prose (from Project Gutenberg, see the
   JSON files in ./texts) or an Owlry reading guide to the recommended
   chapter — labelled as such in the reader, never passed off as the book.
   ============================================================ */
import type { Book } from './types';
import medV from './texts/meditations-v.json';
import neI from './texts/nicomachean-i.json';
import ench from './texts/enchiridion.json';
import shortness from './texts/shortness-of-life.json';

const GUIDE_NOTE = 'An Owlry reading guide to this section — not the book’s text. Open your copy alongside it.';

export const BOOKS_1: Book[] = [
  {
    id: 'meditations',
    title: 'Meditations',
    authorId: 'marcus-aurelius',
    authorName: 'Marcus Aurelius',
    year: 180,
    isbn: '9780140449334',
    category: 'Philosophy',
    axes: ['philosophy'],
    tags: ['Philosophy', 'Stoicism', 'Self-Discipline'],
    palette: { bg: '#2B2A33', fg: '#F3EEE2' },
    blurb: 'A Roman emperor’s private notes to himself on how to stay steady, kind and useful when everything is pulling the other way.',
    quote: {
      text: 'In the morning when thou findest thyself unwilling to rise, consider with thyself presently, it is to go about a man’s work that I am stirred up.',
      source: { work: 'Meditations', loc: 'Book V, 1 (Meric Casaubon translation)', url: 'https://www.gutenberg.org/ebooks/2680' },
    },
    summary: {
      gist: 'Twelve short books of reminders written in the margins of a demanding life. The through-line: you control your judgments and your actions, nothing else — so put your whole self into those and let the rest be.',
      ideas: [
        'Separate what is up to you (your judgments, intentions, effort) from what is not (other people, outcomes, the past).',
        'You were made for work, like a bee for honey — and the work is being a good human today, not being admired later.',
        'Obstacles are raw material: what stands in the way becomes the way.',
        'Think about death often enough that you stop postponing the life you mean to live.',
        'Other people will be difficult. They cannot make you act badly unless you decide to.',
      ],
    },
    start: {
      label: 'Book V',
      title: 'At dawn, when you have trouble getting out of bed',
      why: 'The most practical book of the twelve: it opens with Marcus talking himself out of bed and into the day, which is where every question about discipline actually lives.',
    },
    text: {
      kind: 'public-domain',
      heading: 'Book V',
      note: `${medV.translator} translation, public domain — ${medV.source}.`,
      paragraphs: medV.paragraphs,
    },
  },
  {
    id: 'almanack',
    title: 'The Almanack of Naval Ravikant',
    authorId: 'naval-ravikant',
    authorName: 'Naval Ravikant',
    year: 2020,
    isbn: '9781544514215',
    category: 'Business',
    axes: ['career', 'investing'],
    tags: ['Wealth', 'Judgment', 'Happiness'],
    palette: { bg: '#F4EFE4', fg: '#1E1E1E' },
    blurb: 'A decade of Naval’s tweets, talks and podcasts arranged into a guide to two things he says are learnable: getting wealthy and being happy.',
    quote: {
      text: 'Desire is a contract that you make with yourself to be unhappy until you get what you want.',
      source: { work: 'The Almanack of Naval Ravikant', loc: 'Part II, "Happiness"', url: 'https://www.navalmanack.com/' },
    },
    summary: {
      gist: 'Wealth is assets that earn while you sleep; the way there is specific knowledge, accountability and leverage — code, media, capital, people. Happiness is a skill: a default state you return to when you remove desire, envy and the sense of missing something.',
      ideas: [
        'Seek wealth, not money or status: wealth is ownership of things that compound.',
        'Specific knowledge is found by following genuine curiosity, not what is hot; it cannot be trained for, so it cannot be outsourced.',
        'Play long-term games with long-term people — compounding applies to relationships and reputation, not just interest.',
        'Every desire is a chosen unhappiness; pick one or two big ones and let the rest go.',
        'Happiness is peace, and peace is what remains when you stop wanting the moment to be different.',
      ],
    },
    start: {
      label: 'Part II · Saving Yourself',
      title: 'Choosing to Build Yourself',
      why: 'Naval’s take on discipline is that it is downstream of design — habits, environment, and a self you are consciously building — which is exactly where his view diverges from Marcus’s.',
    },
    text: {
      kind: 'guide',
      heading: 'Choosing to Build Yourself',
      note: GUIDE_NOTE,
      paragraphs: [
        'This section of the Almanack gathers Naval’s remarks on the mechanics of self-improvement, and it opens with a distinction that runs through the whole book: the goal is not to be disciplined, it is to be the kind of person for whom the disciplined action is the easy one. Willpower is treated as a scarce, unreliable resource; habits, environment and identity are treated as the real levers.',
        'Naval describes habits as the units of a life. Every one of them was installed at some point, mostly by accident, and any of them can be uninstalled and replaced — slowly, one at a time. He suggests picking a single habit to change, making the change as small as possible, and treating the first few weeks as an experiment rather than a test of character.',
        'The section also carries his argument about reading: that the ability to read, and the interest to do it, is a learnable habit, and that it may be the single highest-leverage one. His advice is to read what you love until you love to read — a plain reversal of the guilt most people bring to their bookshelf.',
        'What makes this a useful counterweight to the Stoics is the emphasis on leverage. Marcus asks you to rise to the work; Naval asks which work, done consistently, would make most of the other work unnecessary. Both agree that the answer is decided in the morning, by what you actually do, rather than at night, by what you resolve.',
      ],
    },
  },
  {
    id: 'second-sex',
    title: 'The Second Sex',
    authorId: 'simone-de-beauvoir',
    authorName: 'Simone de Beauvoir',
    year: 1949,
    isbn: '9780307277787',
    category: 'Philosophy',
    axes: ['philosophy', 'relationships'],
    tags: ['Existentialism', 'Freedom', 'Feminism'],
    palette: { bg: '#8A2B3F', fg: '#FBEFF0' },
    blurb: 'The book that argued a woman is made, not born — and, underneath that, that any person is a project rather than a fact.',
    quote: {
      text: 'One is not born, but rather becomes, a woman.',
      source: { work: 'The Second Sex', loc: 'Volume II, Part One, ch. 1', url: 'https://openlibrary.org/isbn/9780307277787' },
    },
    summary: {
      gist: 'A thousand pages of biology, history, myth and lived experience making one argument: what looks like a woman’s nature is a situation, and situations can be changed by the people in them. The existentialist premise underneath applies to everyone — you are what you make of what was made of you.',
      ideas: [
        'There is no fixed essence waiting to be expressed; there is a situation, and what you do with it.',
        'Being defined as the "Other" — by a culture, a role, a family — is a trap that can feel like a comfort.',
        'Freedom is not a feeling but a practice: choosing projects and accepting the risk of them.',
        'Independence has a material base — work, money, a life of one’s own — not just an attitude.',
        'To will your own freedom seriously is to will it for others.',
      ],
    },
    start: {
      label: 'Volume II · Part Three',
      title: 'Chapter 14 — The Independent Woman',
      why: 'The chapter where the argument turns practical: what a self-directed life actually costs and requires. Read it as a chapter about anyone trying to choose their own shape.',
    },
    text: {
      kind: 'guide',
      heading: 'The Independent Woman',
      note: GUIDE_NOTE,
      paragraphs: [
        'De Beauvoir opens the chapter with a blunt observation: the vote and the right to work did not, by themselves, make women free. Legal independence and lived independence are different things, and the gap between them is filled with habits, expectations and the quiet economics of who does what at home. She is not writing a complaint; she is describing a mechanism.',
        'The centre of the chapter is work. Economic independence, she argues, is the precondition for every other kind, because a person who cannot support herself must please. But work alone is not enough either: it has to be work chosen as a project, undertaken for its own sake and the future it opens, rather than as a temporary measure before "real" life begins.',
        'She is unsparing about the divided self this produces. The independent woman of 1949 is asked to be two contradictory things at once — to succeed in a world built for men while remaining what that world expects of women — and the cost of the contradiction is paid in fatigue and self-doubt. The point for a reader today is the shape of the trap, which is general: any life split between an authentic project and a role performed for others tends to exhaust the person living it.',
        'The chapter ends on a note that is closer to Naval and Marcus than one might expect. Freedom is not resolved in the abstract; it is exercised, daily, in concrete choices about time, money and attention. Discipline, on this reading, is not obedience to a rule but fidelity to a project one has actually chosen — and de Beauvoir’s test for whether you have chosen it is whether it makes you larger.',
      ],
    },
  },
  {
    id: 'letters-stoic',
    title: 'Letters from a Stoic',
    authorId: 'seneca',
    authorName: 'Seneca',
    year: 65,
    isbn: '9780140442106',
    category: 'Philosophy',
    axes: ['philosophy'],
    tags: ['Stoicism', 'Fear', 'Time'],
    palette: { bg: '#1F3A3A', fg: '#EEF3EF' },
    blurb: 'Letters to a friend about the things that actually derail a life — fear, grief, busyness, old age — from a man who had lived through all of them.',
    quote: {
      text: 'There are more things, Lucilius, likely to frighten us than there are to crush us; we suffer more often in imagination than in reality.',
      source: { work: 'Letters from a Stoic', loc: 'Letter XIII (Richard Gummere translation)', url: 'https://en.wikisource.org/wiki/Moral_letters_to_Lucilius/Letter_13' },
    },
    summary: {
      gist: 'One hundred and twenty-four letters, each a short essay, written late in life to a younger friend. Seneca’s Stoicism is the practical kind: rehearse misfortune, guard your time, keep company with the best minds through their books, and treat every setback as training.',
      ideas: [
        'We suffer more in imagination than in reality — examine the fear before you obey it.',
        'Time is the one possession nobody returns; spend it as carefully as money.',
        'Practise poverty and discomfort on purpose, in small doses, so they lose their power over you.',
        'Read a few authors deeply rather than many shallowly.',
        'Philosophy is not a performance; it shows in how you handle Tuesday.',
      ],
    },
    start: {
      label: 'Letter XIII',
      title: 'On Groundless Fears',
      why: 'The letter to read when a failure has become a forecast. Seneca separates what happened from what you are dreading, and shows how much of the dread is fiction.',
    },
    text: {
      kind: 'guide',
      heading: 'Letter XIII — On Groundless Fears',
      note: GUIDE_NOTE,
      paragraphs: [
        'Seneca begins by paying his friend a compliment — Lucilius has courage — and then withdrawing the reassurance that might follow from it. Courage, he says, is not tested by the blows we have already taken but by the ones we are still expecting. His subject is anticipation: the way a mind facing an uncertain future will build the worst possible version of it and then live inside the building.',
        'The heart of the letter is a sorting exercise. Some of what frightens us is real and imminent; most of it is either exaggerated, imaginary, or premature. Seneca’s advice is to interrogate each fear: what is the actual evidence? What is the actual probability? And even if it comes, what will you actually do? He notes that we are readier to believe a rumour of disaster than a report of good fortune, and that this bias is itself a kind of cowardice.',
        'He does not promise that nothing bad will happen. His argument is narrower and more useful: that suffering in advance doubles the bill, and that the person who waits for trouble before feeling it has, at worst, lost nothing and, at best, been spared entirely. "Do not be unhappy before the crisis comes," he writes, and then gives the corollary — that when it does come, it is rarely as large as it looked from a distance.',
        'For a reader coming to this letter from a failure, the practical move is to write two columns: what you fear will follow, and what you would actually do if it did. Seneca’s claim, borne out by most people who try it, is that the second column is always shorter than the first.',
      ],
    },
  },
  {
    id: 'shortness-of-life',
    title: 'On the Shortness of Life',
    authorId: 'seneca',
    authorName: 'Seneca',
    year: 49,
    isbn: '9780143036326',
    category: 'Philosophy',
    axes: ['philosophy'],
    tags: ['Stoicism', 'Time', 'Attention'],
    palette: { bg: '#2E4A3A', fg: '#EFF3EC' },
    blurb: 'Life is long enough, Seneca argues, if you stop giving it away — a short essay on time that has not aged a day in two thousand years.',
    quote: {
      text: 'It is not that we have a short time to live, but that we waste a lot of it.',
      source: { work: 'On the Shortness of Life', loc: 'ch. 1 (C. D. N. Costa translation)', url: 'https://openlibrary.org/isbn/9780143036326' },
    },
    summary: {
      gist: 'Addressed to his father-in-law, a busy official, the essay argues that the "preoccupied" — people who spend their days on other people’s errands and their own anxieties — are the ones who die too soon, and that the only people who really live are those who make time their own.',
      ideas: [
        'The problem is not the length of a life but the leakage of it.',
        'Busyness is a way of postponing the question of what your life is for.',
        'The past is the only secure possession; the present is brief; the future is not yours.',
        'Reading the great thinkers lets you adopt their years as your own.',
        'Retire — from the crowd, the calendar, the constant claims — before you are too old to use the time.',
      ],
    },
    start: {
      label: 'Chapters I–III',
      title: 'Life is long if you know how to use it',
      why: 'The opening three chapters make the whole argument; everything after is elaboration. Read them in one sitting, then look at your calendar.',
    },
    text: {
      kind: 'public-domain',
      heading: 'Chapters I–III',
      note: `${shortness.translator} translation, public domain — ${shortness.source}.`,
      paragraphs: shortness.paragraphs,
    },
  },
  {
    id: 'atomic-habits',
    title: 'Atomic Habits',
    authorId: 'james-clear',
    authorName: 'James Clear',
    year: 2018,
    isbn: '9780735211292',
    category: 'Self-help',
    axes: ['health', 'career'],
    tags: ['Habits', 'Systems', 'Identity'],
    palette: { bg: '#F2E9D8', fg: '#1E1E1E' },
    blurb: 'The modern manual on getting one percent better: make the good behaviour obvious, attractive, easy and satisfying, and let it compound.',
    quote: {
      text: 'You do not rise to the level of your goals. You fall to the level of your systems.',
      source: { work: 'Atomic Habits', loc: 'ch. 1', url: 'https://openlibrary.org/isbn/9780735211292' },
    },
    summary: {
      gist: 'Habits are the compound interest of self-improvement. Clear’s four laws — cue, craving, response, reward — become a checklist for building any habit and breaking any other, and the deeper claim is that lasting change is a change in identity, voted for one small action at a time.',
      ideas: [
        'Goals set the direction; systems make the progress. Focus on the system.',
        'Every action is a vote for the kind of person you want to be.',
        'Make it obvious, attractive, easy and satisfying — invert each law to break a bad habit.',
        'Environment beats willpower: design the room, not the resolution.',
        'Never miss twice. One slip is an accident; two is the start of a new habit.',
      ],
    },
    start: {
      label: 'Chapter 2',
      title: 'How Your Habits Shape Your Identity (and Vice Versa)',
      why: 'The chapter that turns discipline from a test of character into a question of identity: who are you casting votes for?',
    },
    text: {
      kind: 'guide',
      heading: 'How Your Habits Shape Your Identity (and Vice Versa)',
      note: GUIDE_NOTE,
      paragraphs: [
        'Clear opens with a puzzle: why do habits that we genuinely want to keep — and that would plainly make our lives better — so often fail to stick? His answer is that most people try to change at the wrong layer. There are three: outcomes (what you get), processes (what you do), and identity (what you believe about yourself). Outcome-based habits start from the result; identity-based habits start from who you want to become.',
        'The chapter’s memorable example is two people refusing a cigarette. One says "No thanks, I’m trying to quit." The other says "No thanks, I’m not a smoker." The first is still a smoker who is fighting; the second has changed the story, and the behaviour follows the story with much less friction.',
        'From here Clear introduces the idea of votes. Every action you take, however small, is a piece of evidence for a certain identity. You do not need a unanimous ballot; you need a majority. Missing a day does not undo you. Casting the same small vote most days does, over time, make you someone.',
        'The practical loop the chapter leaves you with is two questions: decide the type of person you want to be, and prove it to yourself with small wins. It is worth noticing how close this sits to Marcus Aurelius’s "be one" and how far it sits from him in method — Clear wants the identity to emerge from the actions, not to be summoned by will at dawn.',
      ],
    },
  },
  {
    id: 'grit',
    title: 'Grit',
    authorId: 'angela-duckworth',
    authorName: 'Angela Duckworth',
    year: 2016,
    isbn: '9781501111105',
    category: 'Psychology',
    axes: ['career'],
    tags: ['Perseverance', 'Practice', 'Purpose'],
    palette: { bg: '#E63946', fg: '#FFFFFF' },
    blurb: 'Why passion plus perseverance predicts achievement better than talent — and how the four ingredients of grit can be grown.',
    quote: { text: 'Enthusiasm is common. Endurance is rare.', source: { work: 'Grit', loc: 'ch. 4', url: 'https://openlibrary.org/isbn/9781501111105' } },
    summary: {
      gist: 'Duckworth’s research at West Point, the National Spelling Bee and beyond found that sticking with long-term goals mattered more than raw ability. Grit, she argues, grows from the inside out — interest, practice, purpose, hope — and from the outside in, through the culture you join.',
      ideas: [
        'Talent counts once; effort counts twice — it builds skill and then makes skill productive.',
        'Interest comes before passion, and it is developed, not discovered.',
        'Deliberate practice — stretch goals, full focus, immediate feedback, repetition — is how experts actually got there.',
        'Purpose, the sense that your work matters to others, is what sustains effort over years.',
        'Join a gritty culture and you will become grittier; conformity is a tool.',
      ],
    },
    start: { label: 'Chapter 7', title: 'Practice', why: 'The chapter on deliberate practice — what disciplined effort looks like when it actually improves you rather than merely tiring you.' },
    text: {
      kind: 'guide',
      heading: 'Practice',
      note: GUIDE_NOTE,
      paragraphs: [
        'Duckworth begins with a finding that surprises most readers: gritty people do not simply practise more, they practise differently. Drawing on Anders Ericsson’s research, she describes deliberate practice — a clearly defined stretch goal, full concentration and effort, immediate and informative feedback, and repetition with refinement — and shows how rarely ordinary "hard work" meets that description.',
        'The chapter is honest about the cost. Deliberate practice is not enjoyable in the way that performing is; spelling-bee champions rated it as the least fun of their study methods and did the most of it anyway. Duckworth’s point is that the discomfort is the signal that you are working at the edge of your ability, which is the only place skill grows.',
        'She closes with a way to make it a habit: same time, same place, same routine, so that the decision to practise is made once rather than daily. For anyone asking how to be more disciplined, the chapter reframes the question — not "how do I push harder?" but "is my effort structured so that it can teach me anything?"',
      ],
    },
  },
  {
    id: 'enchiridion',
    title: 'The Enchiridion',
    authorId: 'epictetus',
    authorName: 'Epictetus',
    year: 125,
    isbn: '9780140449464',
    category: 'Philosophy',
    axes: ['philosophy'],
    tags: ['Stoicism', 'Control', 'Handbook'],
    palette: { bg: '#3A3A4A', fg: '#EFEFF5' },
    blurb: 'The Stoic pocket manual: fifty-three short sections on what is in your control, what is not, and how to live accordingly.',
    quote: { text: 'Some things are in our control and others not.', source: { work: 'The Enchiridion', loc: '§1 (Elizabeth Carter translation)', url: 'https://www.gutenberg.org/ebooks/45109' } },
    summary: {
      gist: 'Compiled by a student from Epictetus’s lectures, the Enchiridion (literally "handbook") begins with the single most important sentence in Stoicism and spends the rest of its length applying it: to grief, ambition, insult, illness and everyday annoyance.',
      ideas: [
        'Your opinions, aims and actions are yours; your body, property and reputation are not.',
        'People are disturbed not by events but by their judgments about events.',
        'Do not demand that things happen as you wish; wish them to happen as they do.',
        'Decide who you want to be, then do what you have to do.',
        'Rehearse the loss of what you love, so that you hold it lightly and lose it gracefully.',
      ],
    },
    start: { label: 'Sections 1–10', title: 'Some things are in our control and others not', why: 'The opening ten sections are the whole philosophy in miniature. If a failure has left you arguing with reality, start here.' },
    text: {
      kind: 'public-domain',
      heading: 'Sections 1–10',
      note: `${ench.translator} translation, public domain — ${ench.source}.`,
      paragraphs: ench.paragraphs,
    },
  },
  {
    id: 'mans-search',
    title: "Man's Search for Meaning",
    authorId: 'viktor-frankl',
    authorName: 'Viktor Frankl',
    year: 1946,
    isbn: '9780807014271',
    category: 'Psychology',
    axes: ['philosophy', 'career'],
    tags: ['Meaning', 'Suffering', 'Freedom'],
    palette: { bg: '#3B4A5A', fg: '#F2F2EE' },
    blurb: 'A psychiatrist’s account of the concentration camps and the theory he took from them: that the will to meaning is the deepest human drive.',
    quote: {
      text: 'When we are no longer able to change a situation, we are challenged to change ourselves.',
      source: { work: "Man's Search for Meaning", loc: 'Part II, "Logotherapy in a Nutshell"', url: 'https://openlibrary.org/isbn/9780807014271' },
    },
    summary: {
      gist: 'Part one is memoir: what Frankl saw in Auschwitz and Dachau, and who survived. Part two is theory: logotherapy, the idea that people can bear almost anything if they have a why. Meaning is found in three places — in work, in love, and in the attitude taken toward unavoidable suffering.',
      ideas: [
        'The last of the human freedoms is to choose one’s attitude in any set of circumstances.',
        'Do not ask what you expect from life; ask what life is asking of you, here, now.',
        'Meaning is found in creating something, in loving someone, or in how you bear what cannot be changed.',
        'Success, like happiness, cannot be pursued; it ensues as the side effect of dedication to something larger.',
        'Tension between what you are and what you ought to become is healthy, not a disorder.',
      ],
    },
    start: { label: 'Part One', title: 'Experiences in a Concentration Camp — the pages on the last of the human freedoms', why: 'For a question about meaningful work, start with the passage where Frankl watches men give away their last piece of bread. It settles what "meaning" means before the theory explains it.' },
    text: {
      kind: 'guide',
      heading: 'Experiences in a Concentration Camp',
      note: GUIDE_NOTE,
      paragraphs: [
        'Frankl is careful, from the first page, about what kind of book this is. It is not a record of the great horrors, which have been documented elsewhere, but of the small ones — the daily experience of an ordinary prisoner — and of the psychology that experience produced. He describes three phases: the shock of arrival, the apathy that follows, and the strange difficulty of liberation.',
        'The pages that most readers remember come in the middle. Frankl writes of prisoners who walked through the huts comforting others and giving away their last piece of bread. They were few, he says, but they offered sufficient proof that everything can be taken from a person except one thing: the freedom to choose one’s attitude in any given set of circumstances.',
        'From this he draws the idea that becomes logotherapy. What sustained those who survived was not physical strength but a future to be responsible for — a manuscript to finish, a child to see again, a task that no one else could do. He quotes Nietzsche: those who have a why to live can bear almost any how. The camps, in his account, were a brutal experiment on the question of what people need, and the answer was meaning.',
        'For someone asking what a meaningful career looks like, the passage reframes the question. Meaning, on Frankl’s account, is not found by looking inward for a passion but by looking outward at what is being asked of you — and answering.',
      ],
    },
  },
  {
    id: 'so-good',
    title: "So Good They Can't Ignore You",
    authorId: 'cal-newport',
    authorName: 'Cal Newport',
    year: 2012,
    isbn: '9781455509126',
    category: 'Business',
    axes: ['career'],
    tags: ['Career', 'Skill', 'Autonomy'],
    palette: { bg: '#1D3557', fg: '#F1FAEE' },
    blurb: 'Why "follow your passion" is bad advice, and what to do instead: build rare skills, then trade them for control and mission.',
    quote: { text: 'Working right trumps finding the right work.', source: { work: "So Good They Can't Ignore You", loc: 'Conclusion', url: 'https://openlibrary.org/isbn/9781455509126' } },
    summary: {
      gist: 'Newport interviews people who love their work and finds that almost none of them started by following a pre-existing passion. They got good at something valuable, accumulated "career capital", and spent it on autonomy and a mission. Passion was the result, not the cause.',
      ideas: [
        'The passion hypothesis is wrong and dangerous: it makes ordinary jobs feel like failures.',
        'Adopt the craftsman mindset — what can I offer? — over the passion mindset — what does this offer me?',
        'Career capital is built with deliberate practice, which most knowledge workers never do.',
        'Control over your work is what makes it feel meaningful, and control has to be bought with capital.',
        'A mission is a small bet placed at the cutting edge of a field you already know well.',
      ],
    },
    start: { label: 'Rule #2', title: 'Be So Good They Can’t Ignore You (Or, the Importance of Skill)', why: 'The chapter with the argument in it: the craftsman mindset versus the passion mindset, and why the first produces the second.' },
    text: {
      kind: 'guide',
      heading: 'Rule #2 — Be So Good They Can’t Ignore You',
      note: GUIDE_NOTE,
      paragraphs: [
        'The rule takes its name from a line of Steve Martin’s, given as advice to aspiring comedians, and Newport uses Martin’s decade of unglamorous stage work to introduce the chapter’s central contrast. The passion mindset asks what the world can offer you and notices, constantly, what is missing. The craftsman mindset asks what you can offer the world and notices, constantly, what could be better.',
        'From there Newport introduces career capital: the rare and valuable skills that are the only currency accepted in exchange for the traits that make work great — autonomy, impact, creativity. He is blunt that most people have very little of it, because most jobs allow you to plateau at "good enough" without ever practising at the edge.',
        'The chapter closes by importing deliberate practice from the study of musicians and chess players into the office: stretch yourself just beyond your current ability, seek honest feedback, and be patient. The connection to the council’s discussion is direct — where Frankl and Campbell start from the inner call, Newport starts from the outer craft, and argues the call tends to arrive once you are good.',
      ],
    },
  },
  {
    id: 'power-of-myth',
    title: 'The Power of Myth',
    authorId: 'joseph-campbell',
    authorName: 'Joseph Campbell',
    year: 1988,
    isbn: '9780385418867',
    category: 'Literature',
    axes: ['literature', 'philosophy'],
    tags: ['Myth', 'Vocation', 'The Hero'],
    palette: { bg: '#5B3A1E', fg: '#F6EFE3' },
    blurb: 'Six conversations with Bill Moyers in which Campbell explains what myths are for — and why "follow your bliss" is a demand, not a permission.',
    quote: {
      text: 'If you follow your bliss, you put yourself on a kind of track that has been there all the while, waiting for you, and the life that you ought to be living is the one you are living.',
      source: { work: 'The Power of Myth', loc: 'ch. 4, "Sacrifice and Bliss"', url: 'https://openlibrary.org/isbn/9780385418867' },
    },
    summary: {
      gist: 'Myths, Campbell argues, are the stories every culture tells to carry people through the stages of a life — leaving home, being tested, returning with something to give. The hero’s journey is a map of that passage, and the modern person, without myths, has to make it alone.',
      ideas: [
        'The hero’s journey — departure, initiation, return — is the shape of every transformation, including a career.',
        'Follow your bliss: the thing that makes you feel most alive is the thread to follow, whatever it costs.',
        'The cave you fear to enter holds the treasure you seek.',
        'Sacrifice is the price of the journey; there is no version without loss.',
        'The privilege of a lifetime is being who you are.',
      ],
    },
    start: { label: 'Chapter 4', title: 'Sacrifice and Bliss', why: 'The chapter with the phrase everyone quotes, in the context that makes it serious: bliss is what you are willing to sacrifice for.' },
    text: {
      kind: 'guide',
      heading: 'Sacrifice and Bliss',
      note: GUIDE_NOTE,
      paragraphs: [
        'The conversation begins with Moyers asking about sacrifice — the strange readiness of people in myths to give up everything — and Campbell answering with stories of parents, soldiers and saints who did exactly that. The point is not that sacrifice is noble in itself, but that it reveals what a person actually values, which is usually not what they say they value.',
        'It is from here that the phrase arrives. Campbell explains that he took "bliss" from the Sanskrit sat-chit-ananda — being, consciousness, rapture — and that, unable to be sure of the first two, he decided to follow the third and trust that it would lead him to the others. Following your bliss, in his usage, is not pleasure-seeking; it is the discipline of noticing what makes you feel fully alive and building a life around it, at the cost of security.',
        'The chapter’s answer to the career question is deliberately uncomfortable. Campbell tells Moyers that most people are living a life of "getting", and that the invisible hands that open doors only appear once you have committed to a path with no guarantee. It is the exact opposite of Cal Newport’s counsel to build skill first — which is why the two belong at the same table.',
      ],
    },
  },
  {
    id: 'human-condition',
    title: 'The Human Condition',
    authorId: 'hannah-arendt',
    authorName: 'Hannah Arendt',
    year: 1958,
    isbn: '9780226025988',
    category: 'Philosophy',
    axes: ['philosophy', 'career'],
    tags: ['Political thought', 'Work', 'Action'],
    palette: { bg: '#4A3A5A', fg: '#F3EEF7' },
    blurb: 'Labour, work and action: Arendt’s anatomy of what people do, and her argument that the highest of the three is beginning something new among others.',
    quote: {
      text: 'Plurality is the condition of human action because we are all the same, that is, human, in such a way that nobody is ever the same as anyone else who ever lived, lives, or will live.',
      source: { work: 'The Human Condition', loc: 'ch. 1, §1', url: 'https://openlibrary.org/isbn/9780226025988' },
    },
    summary: {
      gist: 'Arendt distinguishes labour (the cyclical work of staying alive), work (making durable things), and action (beginning something new in the presence of others) — and argues that modern life has collapsed all three into labour, leaving us busy and unfree.',
      ideas: [
        'Labour leaves nothing behind; work leaves objects; action leaves stories.',
        'Action is only possible in plurality — among people who are equal and distinct.',
        'To act is to begin; every person is, by birth, a new beginning.',
        'Forgiveness and promising are what make action bearable, since we cannot undo or predict what we start.',
        'A society of labourers without labour is the modern danger.',
      ],
    },
    start: { label: 'Chapter V', title: 'Action', why: 'For a question about meaningful work, the chapter that asks which kind of "work" you mean — and argues that the most human kind is the one done among others.' },
    text: {
      kind: 'guide',
      heading: 'Action',
      note: GUIDE_NOTE,
      paragraphs: [
        'Arendt opens the chapter with natality — the fact that each of us was born, and that birth is the arrival of something that has never existed before. Action, in her sense, is the human capacity to repeat that arrival: to begin something new that could not have been predicted from what came before.',
        'Action, she insists, needs others. It happens in a "web of relationships" and its meaning is never fully in the actor’s control, because other people respond, misunderstand, continue and reverse what was begun. This is why action is frightening and why so much of modern life is organised to avoid it — in favour of labour, which is predictable, and work, which at least ends in a product.',
        'For a career, the chapter offers a criterion rather than a plan. Ask of any role: does it let me begin things, in the presence of people who can see me do it? If not, it may be honourable work or necessary labour, but it is not, in Arendt’s terms, action — and it is action that makes a life feel like one’s own.',
      ],
    },
  },
  {
    id: 'letters-young-poet',
    title: 'Letters to a Young Poet',
    authorId: 'rainer-maria-rilke',
    authorName: 'Rainer Maria Rilke',
    year: 1929,
    isbn: '9780393310399',
    category: 'Literature',
    axes: ['literature', 'career'],
    tags: ['Vocation', 'Solitude', 'Patience'],
    palette: { bg: '#5A3A4A', fg: '#F7EEF2' },
    blurb: 'Ten letters to a cadet who wanted to know if he should be a poet — and got, instead, the finest short book on how to be a person.',
    quote: {
      text: 'This most of all: ask yourself in the most silent hour of your night: must I write?',
      source: { work: 'Letters to a Young Poet', loc: 'Letter One (M. D. Herter Norton translation)', url: 'https://openlibrary.org/isbn/9780393310399' },
    },
    summary: {
      gist: 'Rilke declines to judge the young man’s poems and instead tells him how to live: go into yourself, find the necessity, love the questions, be patient with solitude and difficulty, and let the work grow like a tree.',
      ideas: [
        'The only test of a vocation is necessity: would you have to do it if forbidden?',
        'Live the questions now; the answers arrive, if at all, by being lived.',
        'Solitude is not a punishment but the ground of any real work.',
        'Difficulty is not evidence you are on the wrong road; the great things are all difficult.',
        'Love, too, is work — two solitudes that protect and greet each other.',
      ],
    },
    start: { label: 'Letter One', title: 'Must I write?', why: 'The letter that asks the only question that matters about a vocation, and refuses to answer it for you.' },
    text: {
      kind: 'guide',
      heading: 'Letter One',
      note: GUIDE_NOTE,
      paragraphs: [
        'Rilke begins by refusing the request. Franz Kappus has sent poems and asked whether they are good; Rilke replies that nothing is less useful than criticism, and that works of art are infinitely solitary things which no opinion can reach. Then he does the one thing a young writer does not want: he turns the question back.',
        'The instruction that follows is the letter’s centre. Go into yourself. Find out whether the reason you write is spread through the roots of your life. Ask, in the most silent hour of the night, must I? And if the answer is a simple and strong yes, build your life around that necessity — even its most trivial hour must be a sign of it.',
        'For a question about meaningful work the letter is almost too direct. It does not tell you what to do; it tells you how to find out whether you must, and warns that a life built on anything less than a must will be a life spent looking sideways at other people’s lives. Rilke closes by promising that if the answer is no, that too is a gift — it frees the young man to be something else entirely.',
      ],
    },
  },
  {
    id: 'mindset',
    title: 'Mindset',
    authorId: 'carol-dweck',
    authorName: 'Carol Dweck',
    year: 2006,
    isbn: '9780345472328',
    category: 'Psychology',
    axes: ['career', 'health'],
    tags: ['Growth mindset', 'Learning', 'Failure'],
    palette: { bg: '#2A7F8A', fg: '#F4FBFC' },
    blurb: 'The research on why some people are crushed by failure and others are fed by it — and how the difference is a belief you can change.',
    quote: { text: 'Becoming is better than being.', source: { work: 'Mindset', loc: 'ch. 1', url: 'https://openlibrary.org/isbn/9780345472328' } },
    summary: {
      gist: 'People with a fixed mindset believe ability is set; they avoid challenges and read failure as a verdict. People with a growth mindset believe ability grows with effort; they seek challenges and read failure as information. The mindset is learned, and can be relearned.',
      ideas: [
        'The view you adopt of yourself profoundly affects the way you lead your life.',
        'In the fixed mindset, effort is a sign you are not good enough; in the growth mindset, it is how you get good.',
        'Praise effort, strategy and progress, not talent — for yourself as much as for children.',
        'Failure hurts in both mindsets; only in one does it define you.',
        'Add the word "yet".',
      ],
    },
    start: { label: 'Chapter 2', title: 'Inside the Mindsets', why: 'The chapter that shows, through people’s own words, what failure feels like in each mindset — the fastest way to recognise which one you are in right now.' },
    text: {
      kind: 'guide',
      heading: 'Inside the Mindsets',
      note: GUIDE_NOTE,
      paragraphs: [
        'Dweck begins by asking readers to imagine a bad day — a poor grade, a parking ticket, a friend who brushes you off — and to notice what they would think. People in the fixed mindset, her studies found, reach for verdicts: I’m a loser, nothing ever goes right. People in the growth mindset reach for plans: I’ll study harder, I’ll call my friend. Same events, different worlds.',
        'The chapter then walks through the consequences. In the fixed mindset, challenges are threats, effort is shameful, criticism is an attack and other people’s success is a loss. In the growth mindset each of these flips. Dweck is careful to say that the growth mindset does not mean everyone can be anything; it means that a person’s true potential is unknown, and that it is impossible to foresee what years of passion and toil can accomplish.',
        'For a question about failure, the most useful pages are the ones on how each mindset handles a setback. The fixed mindset, she shows, protects itself by blaming, by losing interest, or by deciding the thing was never worth doing. The growth mindset gets curious. The chapter ends with the sentence the council keeps returning to: becoming is better than being.',
      ],
    },
  },
  {
    id: 'antifragile',
    title: 'Antifragile',
    authorId: 'nassim-taleb',
    authorName: 'Nassim Nicholas Taleb',
    year: 2012,
    isbn: '9780812979688',
    category: 'Business',
    axes: ['investing', 'philosophy'],
    tags: ['Risk', 'Volatility', 'Skin in the game'],
    palette: { bg: '#111111', fg: '#F5F5F5' },
    blurb: 'Some things break under stress, some resist it, and some get stronger — and Taleb’s argument is that you should build your life, career and money in the third category.',
    quote: { text: 'Wind extinguishes a candle and energizes fire.', source: { work: 'Antifragile', loc: 'Prologue', url: 'https://openlibrary.org/isbn/9780812979688' } },
    summary: {
      gist: 'Fragile things are harmed by volatility; robust things are unaffected; antifragile things benefit. Bodies, immune systems, restaurants, ideas and careers can be antifragile — if they are exposed to many small stressors, have limited downside, and are free to gain from the upside.',
      ideas: [
        'Small, frequent shocks are how systems learn; the danger is suppressing them until one large shock arrives.',
        'Remove fragilities — debt, dependence, single points of failure — before adding anything clever.',
        'The barbell: be extremely safe in most things and take small, bold risks in a few.',
        'Optionality beats prediction: you do not need to know the future if being wrong is cheap.',
        'Trust only people with skin in the game.',
      ],
    },
    start: { label: 'Prologue', title: 'How to Love the Wind', why: 'Taleb states the whole idea in the prologue: failure is the stressor that makes a system stronger, provided the failure was survivable. Start with that, then decide whether you agree.' },
    text: {
      kind: 'guide',
      heading: 'Prologue — How to Love the Wind',
      note: GUIDE_NOTE,
      paragraphs: [
        'Taleb opens by naming a gap in the language. We have a word for things that break under stress — fragile — and we assume the opposite is robust, the thing that does not break. But the true opposite of fragile is something that gets better under stress, and there was no word for it. He proposes antifragile, and spends the prologue showing how much of life belongs to the category.',
        'The candle-and-fire image is his shorthand. The same wind that extinguishes one feeds the other; the difference is not in the wind but in what it meets. Muscles, bones, immune systems, restaurants, city economies and reputations all belong to the fire side of the ledger: deprived of stressors, they weaken; exposed to small ones, they strengthen.',
        'For a question about failure, the prologue supplies the reframe the council builds on. A failure that was survivable is a stressor, and a stressor is information. What matters is the structure around the failure — whether the downside was capped and whether you are positioned to gain from what it taught you. Taleb’s advice is not to fail less but to arrange your life so that failing is affordable and frequent.',
      ],
    },
  },
  {
    id: 'rising-strong',
    title: 'Rising Strong',
    authorId: 'brene-brown',
    authorName: 'Brené Brown',
    year: 2015,
    isbn: '9780812995824',
    category: 'Psychology',
    axes: ['relationships', 'career'],
    tags: ['Vulnerability', 'Resilience', 'Story'],
    palette: { bg: '#B5651D', fg: '#FFF8F0' },
    blurb: 'What people who fall and get back up actually do: reckon with the feeling, rumble with the story, and rewrite the ending.',
    quote: { text: "The middle is messy, but it's also where the magic happens.", source: { work: 'Rising Strong', loc: 'ch. 2', url: 'https://openlibrary.org/isbn/9780812995824' } },
    summary: {
      gist: 'Brown’s research on people who recover from failure, heartbreak and shame found a three-part process: the reckoning (noticing you are emotionally hooked), the rumble (getting honest about the story you are telling yourself), and the revolution (living the rewritten story).',
      ideas: [
        'You cannot skip the messy middle; the rising happens there.',
        'The story I’m telling myself is… — write the first draft, then look for what you made up.',
        'Curiosity about emotion beats armouring against it.',
        'Everyone is doing the best they can — assuming so changes how you treat them and yourself.',
        'Owning your story is the bravest thing you will ever do.',
      ],
    },
    start: { label: 'Chapter 4', title: 'The Reckoning', why: 'The chapter that begins the process: noticing that a failure has hooked you emotionally, before the story about it hardens.' },
    text: {
      kind: 'guide',
      heading: 'The Reckoning',
      note: GUIDE_NOTE,
      paragraphs: [
        'The reckoning, Brown explains, is not a judgement but a noticing. Something has happened, and you are hooked — by anger, shame, disappointment — and the first move is simply to recognise that you are in it, and to get curious about why. Most people, she found, skip this step entirely and go straight to blaming, numbing or moving on.',
        'She spends the chapter on the ways we avoid the reckoning: chandeliering (stuffing the feeling until it explodes), bouncing hurt into anger, numbing with work or food or scrolling, and stockpiling until the body forces the issue. Each is a way of not knowing what we feel, and each makes the story that follows less true.',
        'The practical instruction is small. Breathe, get curious, and finish the sentence "the story I’m telling myself is…" without editing it. For a question about failure, this is the place to begin: not with the lesson, which comes later, but with an honest account of what it felt like.',
      ],
    },
  },
  {
    id: 'obstacle',
    title: 'The Obstacle Is the Way',
    authorId: 'ryan-holiday',
    authorName: 'Ryan Holiday',
    year: 2014,
    isbn: '9781591846352',
    category: 'Self-help',
    axes: ['philosophy', 'career'],
    tags: ['Stoicism', 'Perception', 'Action'],
    palette: { bg: '#2B2B2B', fg: '#F0EAD6' },
    blurb: 'Marcus Aurelius’s hardest line turned into a method: see the obstacle clearly, act on what you can, and endure the rest.',
    quote: { text: 'The obstacle in the path becomes the path.', source: { work: 'The Obstacle Is the Way', loc: 'Introduction', url: 'https://openlibrary.org/isbn/9781591846352' } },
    summary: {
      gist: 'Built on one passage of the Meditations, the book sorts the Stoic response to adversity into three disciplines — perception, action, will — and illustrates each with people who turned setbacks into advantages.',
      ideas: [
        'Perception: strip the event of the story and see it as it is.',
        'Action: persistence, iteration, and the willingness to try the thing that might work.',
        'Will: accept what cannot be changed and prepare for the next one.',
        'The obstacle is not in your way; it is the way.',
        'Practise on small obstacles so you are ready for large ones.',
      ],
    },
    start: { label: 'Part I', title: 'Perception', why: 'Start with the discipline that comes first: how you see a failure decides everything you will do about it.' },
    text: {
      kind: 'guide',
      heading: 'Part I — Perception',
      note: GUIDE_NOTE,
      paragraphs: [
        'Holiday opens with John D. Rockefeller as a young clerk during the Panic of 1857, watching older men panic while he took notes. The lesson he draws is that the crisis was the same for everyone; the perception of it was not. Perception, in the Stoic sense, is how you interpret what happens, and it is the one thing entirely within reach.',
        'The rest of the part is a set of practices: steady your nerves, control your emotions, practise objectivity, alter your perspective, is it up to you?, live in the present, think differently, find the opportunity, prepare to act. Each is a short chapter with a story, and the cumulative effect is a habit of pausing between the event and the reaction.',
        'For a question about failure, Part I offers a simple exercise. Describe what happened in the plainest possible language, without adjectives, as if reporting it about a stranger. What remains is usually smaller than what you were carrying, and it is the thing you can actually act on.',
      ],
    },
  },
  {
    id: 'nicomachean-ethics',
    title: 'Nicomachean Ethics',
    authorId: 'aristotle',
    authorName: 'Aristotle',
    year: -340,
    isbn: '9780140449495',
    category: 'Philosophy',
    axes: ['philosophy'],
    tags: ['Ethics', 'Flourishing', 'Virtue'],
    palette: { bg: '#5A5A3A', fg: '#F5F3E6' },
    blurb: 'The first systematic answer to "what is a good life?": flourishing, won by a whole life of activity in accordance with virtue.',
    quote: {
      text: 'For one swallow does not make a summer, nor does one day; and so too one day, or a short time, does not make a man blessed and happy.',
      source: { work: 'Nicomachean Ethics', loc: 'Book I, ch. 7 (W. D. Ross translation)', url: 'https://www.gutenberg.org/ebooks/8438' },
    },
    summary: {
      gist: 'Every action aims at some good; the highest good is the one we want for its own sake, and that is eudaimonia — flourishing, or living well. Aristotle argues it consists in activity of the soul in accordance with virtue, over a complete life, with enough friends, health and fortune not to be derailed.',
      ideas: [
        'Happiness is not a feeling but an activity — a way of living, not a state of mind.',
        'Virtue is a mean between excess and deficiency, found by practice until it becomes character.',
        'We become just by doing just acts, brave by doing brave acts.',
        'A good life needs some external goods — friends, resources, luck — but they are not what it is.',
        'Judge a life as a whole; one good day, or one bad one, does not decide it.',
      ],
    },
    start: { label: 'Book I', title: 'Chapters 7–9 — the function of a human being', why: 'The heart of the argument: what a human is for, and therefore what living well means. Read it slowly; every later theory of the good life is a reply to these pages.' },
    text: {
      kind: 'public-domain',
      heading: 'Book I, chapters 7–9',
      note: `${neI.translator} translation, public domain — ${neI.source}.`,
      paragraphs: neI.paragraphs,
    },
  },
  {
    id: 'art-of-happiness',
    title: 'The Art of Happiness',
    authorId: 'epicurus',
    authorName: 'Epicurus',
    year: -300,
    isbn: '9780143107217',
    category: 'Philosophy',
    axes: ['philosophy', 'health'],
    tags: ['Epicureanism', 'Pleasure', 'Friendship'],
    palette: { bg: '#3A6B4A', fg: '#EEF6F0' },
    blurb: 'What survives of Epicurus — letters, maxims and fragments — on how to live without fear and with enough.',
    quote: {
      text: 'Of all the means which are procured by wisdom to ensure happiness throughout the whole of life, by far the most important is the acquisition of friends.',
      source: { work: 'Principal Doctrines', loc: 'XXVII (R. D. Hicks translation)', url: 'https://openlibrary.org/isbn/9780143107217' },
    },
    summary: {
      gist: 'Pleasure is the goal, but pleasure properly understood: the absence of pain in the body and disturbance in the mind. Most of what we chase — wealth, fame, luxury — brings more disturbance than it removes. Friends, simple needs, and freedom from the fear of death and the gods are what actually work.',
      ideas: [
        'Desires are natural and necessary, natural but unnecessary, or neither; happiness lies in satisfying the first and dismissing the third.',
        'Death is nothing to us: where death is, we are not.',
        'Friendship is the single greatest source of a happy life.',
        'Self-sufficiency is a great good — not to have little, but to need little.',
        'Philosophy is medicine for the soul; a doctrine that does not cure suffering is empty.',
      ],
    },
    start: { label: 'Letter to Menoeceus', title: 'On how to live', why: 'The one complete statement of the philosophy in Epicurus’s own words, short enough to read over a cup of tea and long enough to argue with for a lifetime.' },
    text: {
      kind: 'guide',
      heading: 'Letter to Menoeceus',
      note: GUIDE_NOTE,
      paragraphs: [
        'The letter opens with an instruction that is also a rebuke: let no one delay the study of philosophy while young, nor weary of it when old, because no one is too early or too late for the health of the soul. Epicurus then lays out, in order, the things a person must get right to be happy: the gods, death, desire, and the relation between pleasure and virtue.',
        'On the gods he is brief — they exist and they do not concern themselves with us — and on death he is famous. Death is nothing to us, because all good and evil consists in sensation, and death is the end of sensation. Fear of it, he argues, poisons life more than death itself ever could; the person who has genuinely absorbed this can enjoy a mortal life without craving an immortal one.',
        'The section on desire is the practical heart. Some desires are natural and necessary (food, shelter, friendship), some natural but unnecessary (luxury), and some neither (fame, limitless wealth). Happiness follows from satisfying the first group easily, enjoying the second when it comes, and refusing the third entirely. Pleasure, in this account, is a quiet condition — a body free of pain and a mind free of anxiety — and Epicurus insists it cannot be had without prudence, honour and justice.',
        'For the council’s question the letter is the plainest possible alternative to Aristotle: not a life of excellent activity but a life of untroubled ease among friends. Whether that is enough is exactly what the three of them disagree about.',
      ],
    },
  },
  {
    id: 'a-confession',
    title: 'A Confession',
    authorId: 'leo-tolstoy',
    authorName: 'Leo Tolstoy',
    year: 1882,
    isbn: '9780486438511',
    category: 'Philosophy',
    axes: ['philosophy', 'literature'],
    tags: ['Meaning', 'Faith', 'Crisis'],
    palette: { bg: '#4A3A2A', fg: '#F5EFE4' },
    blurb: 'The most famous writer alive, at fifty, asking whether there was any point in living — and the answer he found in people who had never read a book.',
    quote: {
      text: 'What will come of what I am doing today or shall do tomorrow? What will come of my whole life?',
      source: { work: 'A Confession', loc: 'ch. 3 (Aylmer Maude translation)', url: 'https://en.wikisource.org/wiki/A_Confession' },
    },
    summary: {
      gist: 'Tolstoy describes losing his faith, gaining everything a person could want, and finding that success made the question of meaning unbearable rather than irrelevant. Science and philosophy could not answer it. The peasants who worked his land, living by a simple faith, could — not with an argument, but with a life.',
      ideas: [
        'Success does not answer the question of meaning; it makes the question louder.',
        'Reason can describe a life but cannot tell you why to live it.',
        'Look at how ordinary people bear existence before you decide it is unbearable.',
        'Meaning is lived before it is understood.',
        'A faith need not be a doctrine; it can be the working assumption that life is worth the trouble.',
      ],
    },
    start: { label: 'Chapter III', title: 'The question arrives', why: 'The chapter where a man with everything asks what any of it is for. Start here so the rest of the book — and the council — has something to answer.' },
    text: {
      kind: 'guide',
      heading: 'Chapter III',
      note: GUIDE_NOTE,
      paragraphs: [
        'Tolstoy sets the scene with deliberate ordinariness. He is not yet fifty; he has a loving family, a large estate, a body that can mow a field all day, and a reputation greater than any writer’s in Russia. And in the middle of all of it, he writes, something began to happen: moments of perplexity, as if he did not know how to live or what to do, that passed at first and then began to recur.',
        'The moments have the form of a question. What will come of what I am doing today, or tomorrow? What will come of my whole life? He tries to brush it aside as childish and finds that it is the only question worth answering and that he cannot answer it. His work loses its savour; the estate stops mattering; he begins to hide the rope in his study and to stop carrying a gun on his walks.',
        'What makes the chapter more than a memoir of depression is Tolstoy’s insistence that the crisis was rational. Given what he believed about the world — that it was matter in motion and that death ended everything — the question had no answer, and he was simply the one who had noticed. The rest of the book is the search for a belief he could live inside; this chapter is the honest statement of why the search was necessary.',
      ],
    },
  },
  {
    id: 'conquest-of-happiness',
    title: 'The Conquest of Happiness',
    authorId: 'bertrand-russell',
    authorName: 'Bertrand Russell',
    year: 1930,
    isbn: '9780871401625',
    category: 'Philosophy',
    axes: ['philosophy', 'health'],
    tags: ['Happiness', 'Rationalism', 'Interests'],
    palette: { bg: '#2A4A5A', fg: '#EEF4F7' },
    blurb: 'A logician’s brisk, kindly guide to the causes of unhappiness — and the wider interests and affections that cure most of it.',
    quote: {
      text: 'The secret of happiness is this: let your interests be as wide as possible, and let your reactions to the things and persons that interest you be as far as possible friendly rather than hostile.',
      source: { work: 'The Conquest of Happiness', loc: 'ch. 10', url: 'https://openlibrary.org/isbn/9780871401625' },
    },
    summary: {
      gist: 'Most unhappiness, Russell argues, is self-absorption in one of several forms — competition, boredom, fatigue, envy, the sense of sin, fear of public opinion. The cure is outward-facing: work, wide impersonal interests, affection, and a lack of fuss about oneself.',
      ideas: [
        'The unhappy person is usually thinking about themselves.',
        'Zest — a lively interest in things — is the mark of the happy person.',
        'Envy is cured by not comparing, which is a skill.',
        'Effort and resignation both have their place; wisdom is knowing which.',
        'A happy life must be, to a large extent, a quiet life.',
      ],
    },
    start: { label: 'Chapter 10', title: 'Is Happiness Still Possible?', why: 'The pivot from diagnosis to cure, with the book’s central prescription: widen your interests until there is no room left for brooding.' },
    text: {
      kind: 'guide',
      heading: 'Is Happiness Still Possible?',
      note: GUIDE_NOTE,
      paragraphs: [
        'Russell answers his chapter title immediately: yes, and he has met many happy people. He divides them, with characteristic dryness, into those happy through simplicity — his gardener, who has declared war on rabbits and is winning — and those happy through a scientific or artistic absorption that gives their days a shape.',
        'What the happy have in common, he argues, is that they are not the centre of their own attention. Interests directed outward, whether a hobby, a craft, a cause or a friend, occupy the mind that would otherwise turn on itself. From this comes the sentence the chapter is known for: let your interests be as wide as possible, and your reactions to what interests you as friendly as possible.',
        'Set beside Aristotle and Epicurus, Russell is the pragmatist. He does not ask what a human is for or what pleasure really is; he asks what actually makes the people he knows content, and reports the answer. For a reader asking about the good life, the chapter offers a method rather than a definition: acquire an impersonal interest and give it an hour a day.',
      ],
    },
  },
];
