/* ============================================================
   Books, part 2: health / investing / relationships / literature, plus
   the library's extra shelves.
   ============================================================ */
import type { Book } from './types';

const GUIDE_NOTE = 'An Owlry reading guide to this section — not the book’s text. Open your copy alongside it.';

export const BOOKS_2: Book[] = [
  /* ---------------- health ---------------- */
  {
    id: 'wherever-you-go',
    title: 'Wherever You Go, There You Are',
    authorId: 'jon-kabat-zinn',
    authorName: 'Jon Kabat-Zinn',
    year: 1994,
    isbn: '9781401307783',
    category: 'Health',
    axes: ['health', 'philosophy'],
    tags: ['Mindfulness', 'Presence', 'Meditation'],
    palette: { bg: '#4A6B5A', fg: '#F0F6F2' },
    blurb: 'Short, plain chapters on mindfulness as a way of being rather than a technique — from the man who brought meditation into medicine.',
    quote: { text: "You can't stop the waves, but you can learn to surf.", source: { work: 'Wherever You Go, There You Are', loc: 'Part One', url: 'https://openlibrary.org/isbn/9781401307783' } },
    summary: {
      gist: 'Mindfulness is paying attention on purpose, in the present moment, without judgement — and it is simple but not easy. Kabat-Zinn’s chapters are two or three pages each, most ending with a small "try" you can do today.',
      ideas: [
        'The present moment is the only place life actually happens; most of us are elsewhere.',
        'You do not need to stop thinking; you need to stop being run by thinking.',
        'Non-doing is not doing nothing — it is letting things be as they are, which is harder.',
        'Formal practice (sitting) and informal practice (washing dishes) feed each other.',
        'Patience, trust, non-striving and acceptance are attitudes to cultivate, not moods to wait for.',
      ],
    },
    start: { label: 'Part One', title: 'Simple but Not Easy', why: 'The chapter that explains why "just be present" fails as advice — and what practising it actually involves. The mindful counterweight to a habits-and-metrics approach to health.' },
    text: {
      kind: 'guide',
      heading: 'Simple but Not Easy',
      note: GUIDE_NOTE,
      paragraphs: [
        'Kabat-Zinn begins with an admission: mindfulness sounds obvious. Pay attention to the present. Anyone can do it. And then he points out what happens when you try — the mind wanders within seconds, the body itches, the plan for tomorrow arrives — and concludes that the simplicity of the instruction is exactly what makes the practice hard.',
        'The chapter frames the difficulty honestly. Being present is not a state you achieve but a direction you keep turning back toward, hundreds of times, without irritation. The turning back is the practice. Nobody gets better at not wandering; people get better at noticing they have wandered and returning without a story about it.',
        'He connects this to health directly. The body registers the difference between a mind that is here and a mind that is arguing with the past or rehearsing the future; stress lives in the second. For the council’s question about habits, the chapter offers the quiet contrarian view: the problem may not be that you lack a system, but that you are never actually present for the moment in which the choice is made.',
      ],
    },
  },
  {
    id: 'outlive',
    title: 'Outlive',
    authorId: 'peter-attia',
    authorName: 'Peter Attia',
    year: 2023,
    isbn: '9780593236598',
    category: 'Health',
    axes: ['health'],
    tags: ['Longevity', 'Exercise', 'Medicine 3.0'],
    palette: { bg: '#1F5F6B', fg: '#EEF8FA' },
    blurb: 'The science and art of living longer and better: why medicine waits too long, and what to do now for the decade you will care about most.',
    summary: {
      gist: 'Attia argues that the four "horsemen" — heart disease, cancer, neurodegeneration and metabolic dysfunction — take decades to develop and that prevention has to start now. Exercise is the single most powerful tool, followed by nutrition, sleep and emotional health.',
      ideas: [
        'Medicine 2.0 treats disease; Medicine 3.0 prevents it, decades out.',
        'Train for the Centenarian Decathlon: the things you want to still be able to do at eighty.',
        'Exercise beats every drug we have for lifespan and healthspan — strength, stability, VO2 max, zone two.',
        'Nutrition is individual; the reliable rule is enough protein and not too much of anything.',
        'Emotional health is not a nice-to-have; it decides whether the extra years are worth having.',
      ],
    },
    start: { label: 'Chapter 11', title: 'Exercise: The Most Powerful Longevity Drug', why: 'The chapter with the strongest claim in the book, and the evidence for it. If you only change one thing, this is what it should be.' },
    text: {
      kind: 'guide',
      heading: 'Exercise: The Most Powerful Longevity Drug',
      note: GUIDE_NOTE,
      paragraphs: [
        'Attia opens with the numbers. Going from unfit to merely below average in cardiorespiratory fitness cuts mortality risk by roughly half; being in the top quarter versus the bottom is a larger difference than smoking versus not smoking. No drug, he says, comes close, and yet exercise is the intervention doctors are least likely to prescribe with any precision.',
        'The chapter’s organising idea is the Centenarian Decathlon: a list of physical tasks you want to be able to do in your last decade — lift a suitcase into an overhead bin, get up off the floor, carry groceries up stairs, play with a grandchild. Because capacity declines with age, the training you do now has to build a large enough reserve that the decline still leaves you above the line.',
        'He then lays out the four pillars of that training: stability, strength, aerobic efficiency (zone two) and peak aerobic capacity (VO2 max). For someone who cannot stick to healthy habits, the chapter reframes the goal from an abstract "be fit" to a concrete, motivating list of things you refuse to lose — which is, not coincidentally, how James Clear would suggest designing the habit.',
      ],
    },
  },
  {
    id: 'tiny-habits',
    title: 'Tiny Habits',
    authorId: 'bj-fogg',
    authorName: 'BJ Fogg',
    year: 2019,
    isbn: '9780358003328',
    category: 'Self-help',
    axes: ['health'],
    tags: ['Behaviour design', 'Habits', 'Motivation'],
    palette: { bg: '#F5C84C', fg: '#1E1E1E' },
    blurb: 'Behaviour happens when motivation, ability and a prompt meet — so make the behaviour tiny, anchor it, and celebrate.',
    quote: { text: 'Emotions create habits.', source: { work: 'Tiny Habits', loc: 'ch. 5', url: 'https://openlibrary.org/isbn/9780358003328' } },
    summary: {
      gist: 'Fogg’s model, B = MAP, says a behaviour occurs when Motivation, Ability and a Prompt converge. Since motivation is unreliable, make the behaviour so easy it needs almost none, attach it to an existing routine, and feel good immediately — because the feeling, not the repetition, wires the habit.',
      ideas: [
        'Motivation is fickle; design for the days it is low.',
        'Shrink the behaviour until it takes under thirty seconds.',
        'Anchor: after I [existing habit], I will [tiny habit].',
        'Celebrate on the spot — genuinely — to wire it in.',
        'Grow the habit only after it is rooted; never start big.',
      ],
    },
    start: { label: 'Chapter 3', title: 'Ability: Make Things Easy', why: 'The lever most people ignore: not more willpower but less friction. Read it if your habits keep dying in week two.' },
    text: {
      kind: 'guide',
      heading: 'Ability: Make Things Easy',
      note: GUIDE_NOTE,
      paragraphs: [
        'Fogg starts with a confession: for years he thought he had a motivation problem with flossing, and it turned out he had an ability problem — the floss was in a drawer, the habit was "floss all your teeth", and both were just hard enough to lose to a tired evening. He moved the floss and shrank the habit to one tooth, and it has held ever since.',
        'The chapter introduces the Ability Chain — time, money, physical effort, mental effort, routine — and asks which link is weakest for the habit you keep failing. Usually it is one of them, and usually it can be fixed with a change of environment or a smaller starting point rather than a change of character.',
        'For the council’s question, this is the most forgiving voice at the table. Where Attia sets targets and Kabat-Zinn asks for presence, Fogg simply asks you to make the good thing embarrassingly easy — and to notice that the shame of "I should be able to do more" is itself the thing killing the habit.',
      ],
    },
  },
  {
    id: 'miracle-of-mindfulness',
    title: 'The Miracle of Mindfulness',
    authorId: 'thich-nhat-hanh',
    authorName: 'Thich Nhat Hanh',
    year: 1975,
    isbn: '9780807012390',
    category: 'Health',
    axes: ['health', 'philosophy'],
    tags: ['Zen', 'Breathing', 'Everyday practice'],
    palette: { bg: '#5A6B3A', fg: '#F3F6EC' },
    blurb: 'A Zen master’s letter to a friend on how to be fully present while doing the dishes, walking, and breathing — with exercises.',
    quote: {
      text: 'While washing the dishes one should only be washing the dishes, which means that one should be completely aware of the fact that one is washing the dishes.',
      source: { work: 'The Miracle of Mindfulness', loc: 'ch. 1 (Mobi Ho translation)', url: 'https://openlibrary.org/isbn/9780807012390' },
    },
    summary: {
      gist: 'Written as a long letter to a colleague running a school in wartime Vietnam, the book teaches mindfulness as the practice of keeping your attention on what you are doing — with the breath as the anchor — and gives thirty-two exercises for daily life.',
      ideas: [
        'Wash the dishes to wash the dishes, not to get to the tea.',
        'The breath is the bridge between body and mind; return to it.',
        'Keep one day a week entirely mindful, to remember what it feels like.',
        'Every act, done with attention, is a form of meditation.',
        'Peace is not the goal of the path; it is the path.',
      ],
    },
    start: { label: 'Chapter 1', title: 'The Essential Discipline', why: 'The dishwashing chapter — the gentlest argument that discipline and presence are the same thing seen from two sides.' },
    text: {
      kind: 'guide',
      heading: 'The Essential Discipline',
      note: GUIDE_NOTE,
      paragraphs: [
        'The chapter begins with a friend, Allen, describing how having children changed his sense of time: he learned to see his son’s time and his wife’s time as his own, and discovered that he had unlimited time. Thich Nhat Hanh uses the story to introduce the idea that the problem is not too little time but a life divided into "my time" and everything else.',
        'Then come the dishes. He recalls washing up for a hundred monks as a novice with cold water and ashes for soap, and the discovery that there are two ways to do it: to wash the dishes to wash the dishes, or to wash them in order to have a clean kitchen and a cup of tea. The second way, he says, means you are not alive while you wash them — and you will not be alive for the tea either, because you will be thinking of what comes after that.',
        'For someone trying to build healthy habits, the chapter is a quiet challenge to the whole project of "getting through" a routine. The essential discipline is not doing the thing; it is being there while you do it.',
      ],
    },
  },
  {
    id: 'why-we-sleep',
    title: 'Why We Sleep',
    authorId: 'matthew-walker',
    authorName: 'Matthew Walker',
    year: 2017,
    isbn: '9781501144318',
    category: 'Science',
    axes: ['health'],
    tags: ['Sleep', 'Neuroscience', 'Health'],
    palette: { bg: '#1C2A5A', fg: '#EEF1FA' },
    blurb: 'What sleep does for memory, mood, immunity and the length of your life — and what a society that treats it as optional is losing.',
    quote: { text: 'Sleep is the single most effective thing we can do to reset our brain and body health each day.', source: { work: 'Why We Sleep', loc: 'ch. 7', url: 'https://openlibrary.org/isbn/9781501144318' } },
    summary: {
      gist: 'Walker walks through the science of the two systems that govern sleep, what each stage does, and the cost of not getting enough — to learning, emotional regulation, the heart, and the immune system. The prescription is unglamorous: eight hours, regular, dark, cool.',
      ideas: [
        'Short sleep does not just make you tired; it makes you worse at nearly everything, and you cannot feel how much.',
        'Regularity matters as much as duration.',
        'Alcohol and late caffeine both fragment sleep in ways that feel fine and are not.',
        'Sleep before learning prepares the brain; sleep after learning saves what was learned.',
        'Dreaming REM sleep is emotional first aid.',
      ],
    },
    start: { label: 'Chapter 7', title: 'Sleep Deprivation and the Brain', why: 'The chapter that makes the case that every other health habit sits on top of this one.' },
    text: {
      kind: 'guide',
      heading: 'Sleep Deprivation and the Brain',
      note: GUIDE_NOTE,
      paragraphs: [
        'Walker opens with the ways short sleep damages attention, using the microsleep — the two-second lapse in which the brain simply goes offline — to explain why drowsy driving kills more people than alcohol and drugs combined. The unsettling finding is that people who sleep six hours a night for ten days perform as badly as people kept awake for a full twenty-four, and rate themselves as fine.',
        'The chapter then turns to emotion. Without enough sleep the amygdala over-reacts and the prefrontal cortex under-controls, producing the swings between irritability and giddiness that anyone who has pulled an all-nighter recognises. Memory suffers in both directions: the sleep-deprived brain neither takes in new information well nor keeps it.',
        'For a question about healthy habits, the chapter reorders the list. Diet and exercise are downstream of sleep, because the willpower, mood and energy they require are the first things sleep loss removes. Walker’s advice is to treat an eight-hour sleep opportunity as the non-negotiable that makes the rest possible.',
      ],
    },
  },

  /* ---------------- investing ---------------- */
  {
    id: 'intelligent-investor',
    title: 'The Intelligent Investor',
    authorId: 'benjamin-graham',
    authorName: 'Benjamin Graham',
    year: 1949,
    isbn: '9780060555665',
    category: 'Investing',
    axes: ['investing'],
    tags: ['Value investing', 'Margin of safety', 'Mr. Market'],
    palette: { bg: '#2A3A2A', fg: '#F1F4EE' },
    blurb: 'The book Warren Buffett calls the best on investing ever written: how to think about price, value, risk and your own worst enemy.',
    quote: { text: "The investor's chief problem — and even his worst enemy — is likely to be himself.", source: { work: 'The Intelligent Investor', loc: 'Introduction', url: 'https://openlibrary.org/isbn/9780060555665' } },
    summary: {
      gist: 'Graham separates investment from speculation, the defensive investor from the enterprising one, and price from value. His two great images — Mr. Market, the manic business partner who quotes you a price every day, and the margin of safety — are the foundation of value investing.',
      ideas: [
        'An investment operation promises safety of principal and an adequate return; everything else is speculation.',
        'Mr. Market is there to serve you, not to guide you.',
        'Always insist on a margin of safety: a price well below what the business is worth.',
        'The defensive investor should own a diversified, boring portfolio and leave it alone.',
        'Temperament, not intelligence, decides investment results.',
      ],
    },
    start: { label: 'Chapter 8', title: 'The Investor and Market Fluctuations', why: 'The Mr. Market chapter. Read it before you look at a price chart, and you will never look at one the same way.' },
    text: {
      kind: 'guide',
      heading: 'The Investor and Market Fluctuations',
      note: GUIDE_NOTE,
      paragraphs: [
        'Graham begins by conceding the obvious: prices will fluctuate, sometimes wildly, and the investor should expect it. The question is what to do about it. He describes two ways of trying to profit — timing (predicting the market) and pricing (buying below value) — and argues that only the second is investing; timing is a game in which the amateur is the house’s favourite customer.',
        'Then comes the parable. Imagine you own a share of a private business with a partner named Mr. Market. Every day he tells you what he thinks your interest is worth and offers to buy you out or sell you more at that price. Some days his figure is sensible; often it is absurd, swinging with his mood. You are free to ignore him. His quotations are useful only when they are foolish — when he offers to buy at a silly high price, or sell at a silly low one.',
        'The chapter closes with the point the council builds on: the real danger to an investor is not the market’s mood but their own. The person who lets Mr. Market’s panic become their panic has turned an advantage into a disadvantage. For a beginner, Graham’s counsel is to decide your policy in calm weather and then refuse to renegotiate it in a storm.',
      ],
    },
  },
  {
    id: 'little-book',
    title: 'The Little Book of Common Sense Investing',
    authorId: 'john-bogle',
    authorName: 'John C. Bogle',
    year: 2007,
    isbn: '9781119404507',
    category: 'Investing',
    axes: ['investing'],
    tags: ['Index funds', 'Costs', 'Simplicity'],
    palette: { bg: '#6B1F1F', fg: '#FBEFEF' },
    blurb: 'The founder of Vanguard on the only way to guarantee your fair share of stock market returns: own everything, pay almost nothing, and stay the course.',
    quote: { text: "Don't look for the needle in the haystack. Just buy the haystack!", source: { work: 'The Little Book of Common Sense Investing', loc: 'ch. 1', url: 'https://openlibrary.org/isbn/9781119404507' } },
    summary: {
      gist: 'Investors as a group earn the market’s return before costs and less than it after costs. The relentless arithmetic of fees, taxes and trading means the low-cost index fund wins over decades not sometimes but reliably — and the investor’s job is mostly to do nothing.',
      ideas: [
        'Costs matter enormously, because they compound too.',
        'Nobody beats the market reliably after costs, including the people paid to.',
        'Buy the whole haystack: a broad index fund holds every needle.',
        'Time is your friend; impulse is your enemy.',
        'Simplicity is not a compromise; it is the strategy.',
      ],
    },
    start: { label: 'Chapter 1', title: 'A Parable', why: 'The Gotrocks family: the whole argument told as a story about a family that owned everything and hired helpers. Ten minutes, and you will understand fees forever.' },
    text: {
      kind: 'guide',
      heading: 'A Parable',
      note: GUIDE_NOTE,
      paragraphs: [
        'Bogle borrows a story from Warren Buffett. Once upon a time the Gotrocks family owned every share of every company in the country, and each year they collected all the dividends and all the growth. Then some Helpers arrived, offering to help individual family members outsmart their cousins by trading shares among themselves. The trading added nothing to the family’s total; the Helpers’ fees subtracted from it.',
        'More Helpers followed — consultants to choose the Helpers, managers to manage the managers — each taking a slice, until the family’s share of what the businesses actually earned had shrunk substantially. The family, at last, notices that all this activity has simply moved money from Gotrocks pockets to Helper pockets, and returns to the original arrangement: own everything, pay no one, and collect.',
        'For someone asking how to start investing, the parable is the fastest possible education in the one variable you fully control. Where Graham asks you to master your temperament and Housel asks you to understand your own psychology, Bogle asks only that you refuse to feed the Helpers.',
      ],
    },
  },
  {
    id: 'psychology-of-money',
    title: 'The Psychology of Money',
    authorId: 'morgan-housel',
    authorName: 'Morgan Housel',
    year: 2020,
    isbn: '9780857197689',
    category: 'Investing',
    axes: ['investing', 'philosophy'],
    tags: ['Behaviour', 'Enough', 'Compounding'],
    palette: { bg: '#F3EEE3', fg: '#1A1A1A' },
    blurb: 'Nineteen short stories about the strange ways people think about money — and why behaving well matters more than knowing a lot.',
    quote: { text: 'Doing well with money has a little to do with how smart you are and a lot to do with how you behave.', source: { work: 'The Psychology of Money', loc: 'Introduction', url: 'https://openlibrary.org/isbn/9780857197689' } },
    summary: {
      gist: 'Money is not a maths problem but a behaviour problem. Housel argues that everyone’s financial decisions make sense given their own history, that luck and risk are siblings, that "enough" is the most important number, and that the true dividend of wealth is control over your time.',
      ideas: [
        'No one is crazy: people’s money decisions follow their experiences, not the textbook.',
        'The hardest financial skill is getting the goalposts to stop moving.',
        'Compounding is the eighth wonder, and its secret is time, not returns.',
        'Getting wealthy and staying wealthy are different skills; the second needs humility and fear.',
        'The highest form of wealth is waking up and doing what you want, with whom you want, for as long as you want.',
      ],
    },
    start: { label: 'Chapter 3', title: 'Never Enough', why: 'The chapter to read before any strategy: it is about the one decision — what enough looks like — that decides whether a strategy can ever succeed.' },
    text: {
      kind: 'guide',
      heading: 'Never Enough',
      note: GUIDE_NOTE,
      paragraphs: [
        'Housel opens with Rajat Gupta and Bernie Madoff — two men who had more money than they could ever spend and risked all of it for more — and asks the only question that matters: why? His answer is that they had no sense of enough. The goalposts kept moving, and when ambition outruns satisfaction the result is not more but ruin.',
        'From there he offers four ideas. The hardest financial skill is getting the goalpost to stop moving. Social comparison is the problem — there is always someone richer, so the ceiling is infinite. "Enough" is not too little; it is the realisation that an insatiable appetite for more will push you to regret. And there are many things never worth risking, no matter the potential gain: reputation, freedom, family, friends, happiness.',
        'For a beginner, the chapter is the deliberate opposite of a stock tip. Before Graham’s margin of safety or Bogle’s index fund can do their work, you need a number you would be content with — otherwise every gain becomes the new baseline and the whole exercise becomes a treadmill.',
      ],
    },
  },
  {
    id: 'poor-charlies',
    title: "Poor Charlie's Almanack",
    authorId: 'charlie-munger',
    authorName: 'Charlie Munger',
    year: 2005,
    isbn: '9781578645015',
    category: 'Investing',
    axes: ['investing', 'philosophy'],
    tags: ['Mental models', 'Inversion', 'Judgment'],
    palette: { bg: '#3A3A2A', fg: '#F3F1E8' },
    blurb: 'Munger’s talks on worldly wisdom: the latticework of mental models, the psychology of misjudgment, and inverting every problem.',
    quote: { text: 'Invert, always invert.', source: { work: "Poor Charlie's Almanack", loc: 'Talk Two (quoting the mathematician Jacobi)', url: 'https://openlibrary.org/isbn/9781578645015' } },
    summary: {
      gist: 'A collection of Munger’s speeches, arranged with his own commentary. The recurring argument is that good decisions come from a wide set of models drawn from many disciplines, a hard-won understanding of how the mind fools itself, and the habit of asking what would guarantee failure.',
      ideas: [
        'A man with only one model is a man with a hammer.',
        'Invert: figure out what you want to avoid, then avoid it.',
        'Incentives are the most underrated force in human behaviour.',
        'Avoiding stupidity is easier than seeking brilliance.',
        'Take a simple idea and take it seriously.',
      ],
    },
    start: { label: 'Talk Eleven', title: 'The Psychology of Human Misjudgment', why: 'Munger’s catalogue of the twenty-five ways minds go wrong with money. The best possible companion to Housel, and considerably funnier.' },
    text: {
      kind: 'guide',
      heading: 'The Psychology of Human Misjudgment',
      note: GUIDE_NOTE,
      paragraphs: [
        'Munger explains that he assembled his list of psychological tendencies himself, because the psychology textbooks of his youth ignored the very things that mattered most to a practical person. He then walks through them: reward and punishment superresponse, liking and disliking, doubt-avoidance, inconsistency-avoidance, envy, reciprocation, social proof, and the lollapalooza effect that occurs when several combine.',
        'Each tendency comes with an antidote, and the antidotes are the point. Against incentive-caused bias: distrust the advice of anyone paid by the outcome. Against social proof: ignore what everyone else is doing, especially in a market. Against inconsistency-avoidance: hold your conclusions loosely and be willing to destroy a favourite idea once a year.',
        'For a beginning investor, the talk is a map of the mistakes waiting in the first bull market and the first crash. Munger’s counsel is to read the list, recognise yourself in it, and design your process so that your worst tendencies cannot reach the buy button.',
      ],
    },
  },
  {
    id: 'essays-buffett',
    title: 'The Essays of Warren Buffett',
    authorId: 'warren-buffett',
    authorName: 'Warren Buffett',
    year: 1997,
    isbn: '9780966446104',
    category: 'Investing',
    axes: ['investing'],
    tags: ['Business ownership', 'Long term', 'Temperament'],
    palette: { bg: '#2A4A2A', fg: '#EFF5EE' },
    blurb: 'Buffett’s letters to Berkshire shareholders, arranged by theme: the plainest, most patient explanation of investing ever written by the person best at it.',
    quote: { text: 'Be fearful when others are greedy and greedy only when others are fearful.', source: { work: 'The Essays of Warren Buffett', loc: 'from the 1986 letter to shareholders', url: 'https://openlibrary.org/isbn/9780966446104' } },
    summary: {
      gist: 'Edited by Lawrence Cunningham, the Essays collect Buffett’s annual letters by subject. The lessons are consistent across decades: think like a business owner, stay inside your circle of competence, treat volatility as opportunity, and let time and a few good decisions do the work.',
      ideas: [
        'Buy businesses, not tickers; if you would not own it for ten years, do not own it for ten minutes.',
        'Stay inside your circle of competence, and know where its edge is.',
        'Mr. Market is your servant, not your master.',
        'Wide diversification is only required when investors do not understand what they are doing.',
        'For most people, a low-cost index fund is the right answer.',
      ],
    },
    start: { label: 'Investing', title: 'The "Mr. Market" essay', why: 'Buffett retelling his teacher Graham’s parable in his own words, with forty years of practice behind it.' },
    text: {
      kind: 'guide',
      heading: 'Mr. Market',
      note: GUIDE_NOTE,
      paragraphs: [
        'Buffett introduces Graham’s Mr. Market as the most important lesson he ever learned about investing, and retells it with the affection of a former student: the obliging partner who appears daily with a price, sometimes euphoric, sometimes despondent, always willing to transact, and never offended if ignored.',
        'He then draws the practical conclusions. Mr. Market’s job is to serve you, not to guide you. An investor who cannot handle a fifty percent drop in the quoted price of a holding without panicking should not be in the market. And the only reason to pay attention to prices is to buy from Mr. Market when he is depressed and, occasionally, to sell to him when he is manic.',
        'The essay ends where the council does: with temperament. Buffett is explicit that success in investing does not correlate with IQ once you are above a modest threshold; what is needed is the temperament to control the urges that get other people into trouble.',
      ],
    },
  },

  /* ---------------- relationships ---------------- */
  {
    id: 'art-of-loving',
    title: 'The Art of Loving',
    authorId: 'erich-fromm',
    authorName: 'Erich Fromm',
    year: 1956,
    isbn: '9780061129735',
    category: 'Relationships',
    axes: ['relationships', 'philosophy'],
    tags: ['Love', 'Practice', 'Psychoanalysis'],
    palette: { bg: '#7A2A2A', fg: '#FBEFEF' },
    blurb: 'Love is not a feeling that happens to you but an art you practise, with the same discipline and patience as any other craft.',
    quote: { text: "Immature love says: 'I love you because I need you.' Mature love says: 'I need you because I love you.'", source: { work: 'The Art of Loving', loc: 'ch. 2', url: 'https://openlibrary.org/isbn/9780061129735' } },
    summary: {
      gist: 'Fromm argues that most people think the problem of love is being loved, or finding the right object, when it is really the problem of one’s own capacity to love. Love is an activity — giving, care, responsibility, respect, knowledge — and like any art it needs discipline, concentration and patience.',
      ideas: [
        'Love is an activity, not a passive affect; a standing in, not a falling for.',
        'Giving is the highest expression of potency, not a sacrifice.',
        'Care, responsibility, respect and knowledge are the elements common to all forms of love.',
        'Modern culture treats love as an exchange of attractive packages.',
        'The practice of any art requires discipline, concentration, patience and supreme concern.',
      ],
    },
    start: { label: 'Chapter 2', title: 'The Theory of Love', why: 'The chapter that defines love as an activity with four elements — the definition every other voice at the table is arguing with.' },
    text: {
      kind: 'guide',
      heading: 'The Theory of Love',
      note: GUIDE_NOTE,
      paragraphs: [
        'Fromm begins with the human condition: we are the only animals aware of our separateness, and the anxiety of that separateness is the source of every attempt at union — orgiastic states, conformity, creative work, and love. Love is the only one that unites without destroying the individual; it is union under the condition of preserving one’s integrity.',
        'He then dismantles the idea of love as passivity. Love is an activity, and its character is giving. Not giving up, not sacrifice, but the expression of aliveness: the person who gives their joy, interest, understanding and humour to another enriches themselves in the giving. From this follow the four elements — care (active concern for the other’s growth), responsibility (the readiness to respond), respect (seeing the other as they are), and knowledge (going into the other’s depth rather than one’s own projection).',
        'The chapter ends by distinguishing the objects of love — brotherly, motherly, erotic, self-love and the love of God — and insisting that a person who can love only one other person, and no one else, has not learned to love but to attach. For the council’s question about deeper relationships, Fromm’s answer arrives before any technique: the depth is in you, and it is practised.',
      ],
    },
  },
  {
    id: 'all-about-love',
    title: 'All About Love',
    authorId: 'bell-hooks',
    authorName: 'bell hooks',
    year: 2000,
    isbn: '9780060959470',
    category: 'Relationships',
    axes: ['relationships'],
    tags: ['Love ethic', 'Justice', 'Community'],
    palette: { bg: '#7A4A6B', fg: '#F9F0F6' },
    blurb: 'We talk about love constantly and define it never — hooks gives it a definition, an ethic, and a politics.',
    quote: {
      text: 'To truly love we must learn to mix various ingredients — care, affection, recognition, respect, commitment, and trust, as well as honest and open communication.',
      source: { work: 'All About Love', loc: 'ch. 1', url: 'https://openlibrary.org/isbn/9780060959470' },
    },
    summary: {
      gist: 'Borrowing M. Scott Peck’s definition — love as the will to extend oneself for the purpose of nurturing one’s own or another’s spiritual growth — hooks argues that love is an action, that it cannot coexist with abuse or domination, and that a culture which sentimentalises love has stopped practising it.',
      ideas: [
        'Love is as love does: an act of will, both intention and action.',
        'Abuse and love cannot coexist; where there is domination there is not love.',
        'Most of us learned love as a feeling and were never taught it as a practice.',
        'A love ethic extends from the couple to the community and the culture.',
        'Honesty is the ground of love; lies, even kind ones, corrode it.',
      ],
    },
    start: { label: 'Chapter 1', title: 'Clarity: Give Love Words', why: 'The chapter that asks what you actually mean by the word — and gives a definition strict enough to be useful.' },
    text: {
      kind: 'guide',
      heading: 'Clarity: Give Love Words',
      note: GUIDE_NOTE,
      paragraphs: [
        'hooks opens with her own childhood, and with a question she could not answer: how can a home be both loving and abusive? Her conclusion is that it cannot — that what she had been taught to call love was something else — and that the confusion is general. Everyone talks about love; almost no one defines it.',
        'She adopts Peck’s definition and draws out what follows. If love is the will to nurture growth, it is a choice and an action, not a feeling; feelings arise on their own, but we choose whether to love. This makes it possible to say, of any relationship, whether love is present — by looking at what is done, not what is felt.',
        'The chapter’s ingredients list — care, affection, recognition, respect, commitment, trust, honest and open communication — is offered as a practical instrument. For someone asking how to build deeper relationships, hooks’s first instruction is diagnostic: look at your closest relationships and name which ingredients are present and which are missing. The depth you want is in the missing ones.',
      ],
    },
  },
  {
    id: 'mating-in-captivity',
    title: 'Mating in Captivity',
    authorId: 'esther-perel',
    authorName: 'Esther Perel',
    year: 2006,
    isbn: '9780060753641',
    category: 'Relationships',
    axes: ['relationships'],
    tags: ['Desire', 'Intimacy', 'Long-term love'],
    palette: { bg: '#8A2A4A', fg: '#FBEFF3' },
    blurb: 'Why security and desire pull in opposite directions in long relationships — and how to keep both alive.',
    quote: { text: 'Love enjoys knowing everything about you; desire needs mystery.', source: { work: 'Mating in Captivity', loc: 'ch. 2', url: 'https://openlibrary.org/isbn/9780060753641' } },
    summary: {
      gist: 'Perel argues that modern couples ask one relationship to provide everything — stability, belonging, passion, adventure — and that the last two need distance, separateness and a little uncertainty, which the first two work to eliminate. The answer is not less intimacy but a different kind of space.',
      ideas: [
        'Love seeks closeness; desire needs distance.',
        'Fire needs air — and a couple that has fused has none.',
        'Seeing your partner as a separate person, from across a room, is where wanting returns.',
        'Domesticity and eroticism are not enemies, but they need to be negotiated, not merged.',
        'Playfulness is not frivolous; it is how adults keep desire alive.',
      ],
    },
    start: { label: 'Chapter 2', title: 'More Intimacy, Less Sex', why: 'The chapter with the paradox in it: the closeness the other voices prescribe is exactly what Perel says can smother desire.' },
    text: {
      kind: 'guide',
      heading: 'More Intimacy, Less Sex',
      note: GUIDE_NOTE,
      paragraphs: [
        'Perel introduces a couple from her practice who have done everything right — they talk, they share, they know each other completely — and who have not touched each other in a year. The chapter’s argument grows from that case: intimacy of the confessional kind, in which nothing is withheld, can produce a closeness so total that there is nothing left to reach for.',
        'She contrasts two needs. Love wants to know, to merge, to shrink the distance; desire wants to explore, to be surprised, to cross a distance. Both are legitimate, and modern coupledom, by treating transparency as the highest value, has quietly starved the second.',
        'Her prescription, which the council debates, is not mystery for its own sake but separateness: keeping a self that is not entirely available, seeing one’s partner as a person with a life apart, cultivating the little uncertainties that make wanting possible. For a question about deeper relationships, Perel is the voice that asks whether "deeper" always means "closer".',
      ],
    },
  },
  {
    id: 'four-loves',
    title: 'The Four Loves',
    authorId: 'cs-lewis',
    authorName: 'C. S. Lewis',
    year: 1960,
    isbn: '9780156329309',
    category: 'Relationships',
    axes: ['relationships', 'philosophy'],
    tags: ['Affection', 'Friendship', 'Eros', 'Charity'],
    palette: { bg: '#3A5A6B', fg: '#EEF4F8' },
    blurb: 'Affection, friendship, eros and charity — four different things we call by one name, and what each asks of us.',
    quote: { text: 'To love at all is to be vulnerable.', source: { work: 'The Four Loves', loc: 'ch. 6', url: 'https://openlibrary.org/isbn/9780156329309' } },
    summary: {
      gist: 'Lewis sorts love into four kinds from the Greek — storge (affection), philia (friendship), eros (romance) and agape (charity) — shows how each can go wrong when it tries to be the whole of love, and ends with the argument that the risk of being hurt is the price of loving anything at all.',
      ideas: [
        'Affection is the humblest love and the most easily taken for granted.',
        'Friendship is about something; lovers face each other, friends stand side by side.',
        'Eros makes a man really want, not a woman, but one particular woman.',
        'Any love that becomes a god becomes a demon.',
        'To love at all is to be vulnerable; the only safe place is hell.',
      ],
    },
    start: { label: 'Chapter 4', title: 'Friendship', why: 'The neglected love, and the chapter most relevant to a question about depth: Lewis thinks friendship is where much of it lives.' },
    text: {
      kind: 'guide',
      heading: 'Friendship',
      note: GUIDE_NOTE,
      paragraphs: [
        'Lewis observes that the modern world barely recognises friendship as a love at all — it is the least natural, the least biological, the least necessary; nobody needs a friend the way a child needs a mother. And precisely for that reason, he argues, it is the freest and in some ways the highest: chosen, unforced, and about something beyond the two people.',
        'His picture of friendship is two people who discover they see the same truth, or care about the same thing, and say to one another "What? You too? I thought I was the only one." Lovers are normally face to face, absorbed in each other; friends are side by side, absorbed in a common interest. This is why, he says, friendship is the least jealous of loves: two friends delight to be joined by a third.',
        'For the council’s question the chapter offers a corrective. The depth people seek in romance is often available, and more durable, in friendship — and a marriage in which the partners are not also friends, side by side about something, has lost the sturdiest of the four.',
      ],
    },
  },
  {
    id: 'seven-principles',
    title: 'The Seven Principles for Making Marriage Work',
    authorId: 'john-gottman',
    authorName: 'John Gottman',
    year: 1999,
    isbn: '9780553447712',
    category: 'Relationships',
    axes: ['relationships'],
    tags: ['Research', 'Marriage', 'Repair'],
    palette: { bg: '#2A5A4A', fg: '#EEF6F2' },
    blurb: 'Forty years of watching couples in a lab, distilled into seven things the ones who last actually do.',
    quote: { text: 'Happy marriages are based on a deep friendship.', source: { work: 'The Seven Principles for Making Marriage Work', loc: 'ch. 1', url: 'https://openlibrary.org/isbn/9780553447712' } },
    summary: {
      gist: 'Gottman’s "Love Lab" found that stable couples are not those who never fight but those who maintain a five-to-one ratio of positive to negative interactions, repair quickly, and keep the four horsemen — criticism, contempt, defensiveness, stonewalling — out of the house. The principles are practical and testable.',
      ideas: [
        'Enhance your love maps: know the details of your partner’s inner world.',
        'Turn toward, not away, in the small daily bids for attention.',
        'Contempt is the single best predictor of divorce.',
        'Most conflict is perpetual; the goal is dialogue, not resolution.',
        'Create shared meaning — rituals, roles, goals — so the marriage is about something.',
      ],
    },
    start: { label: 'Principle 1', title: 'Enhance Your Love Maps', why: 'The most concrete answer at the table: depth is a matter of detail, and the chapter comes with a questionnaire.' },
    text: {
      kind: 'guide',
      heading: 'Enhance Your Love Maps',
      note: GUIDE_NOTE,
      paragraphs: [
        'Gottman introduces the love map as the part of your brain where you store the relevant information about your partner’s life: their worries, their hopes, who their friends are, what happened at work on Tuesday. Couples with detailed love maps, his research found, weather stress and transitions — a first baby, a job loss — far better than those who have stopped updating.',
        'The chapter is unusually concrete. It includes a twenty-question quiz (What is my partner’s favourite way to spend an evening? Who is my partner’s greatest source of support besides me?) and a set of exercises for filling the gaps: open-ended questions, deliberate curiosity, and the habit of asking about the day and then actually listening.',
        'Set against Fromm and hooks, Gottman is the empiricist. Where they define love, he measures it; and his measurement suggests that depth, in practice, is largely knowledge — the accumulation of small facts that tell your partner they are seen.',
      ],
    },
  },
  {
    id: 'course-of-love',
    title: 'The Course of Love',
    authorId: 'alain-de-botton',
    authorName: 'Alain de Botton',
    year: 2016,
    isbn: '9780241145470',
    category: 'Literature',
    axes: ['relationships', 'literature'],
    tags: ['Novel', 'Marriage', 'Realism'],
    palette: { bg: '#5A4A6B', fg: '#F3EFF8' },
    blurb: 'A novel that begins where love stories end — at the wedding — and follows one couple through the sulks, laundry and slow work of staying.',
    summary: {
      gist: 'Rabih and Kirsten meet, marry, and then the book keeps going: through money arguments, parenthood, an affair, and the discovery that love is a skill to be learned rather than an enthusiasm to be felt. Essayistic passages interrupt the story to say what the characters cannot.',
      ideas: [
        'Romanticism taught us to expect instinct; love is a skill, and we are all beginners.',
        'The person "right" for us is the one who can negotiate differences intelligently.',
        'Sulking is a strange demand to be understood without explaining.',
        'Maturity is accepting that we are, in specific ways, hard to live with.',
        'Love is not the intensity at the start but the patience in the middle.',
      ],
    },
    start: { label: 'Ever After', title: 'Silly Things', why: 'The chapter on the first small fights — where de Botton argues most of love is actually decided.' },
    text: {
      kind: 'guide',
      heading: 'Silly Things',
      note: GUIDE_NOTE,
      paragraphs: [
        'The section follows Rabih and Kirsten into their first year of marriage and the first arguments, which are never about what they seem to be about: a set of glasses bought without consultation, a temperature setting, the way one of them says "fine". De Botton’s narrator steps in to observe that the ability to fight well about small things is a better predictor of a marriage than the intensity of its beginning.',
        'The chapter’s essayistic interludes make the argument the story dramatises. We arrive at love with a Romantic script — that the right person will understand us without words, that love should be effortless — and the script sets us up to read every friction as evidence that we have chosen wrongly. Maturity, in his account, is replacing the script with a more modest one.',
        'For a question about deeper relationships, the chapter is the novelist’s version of Gottman’s data: depth is what is built in the handling of the trivial, and the couple who can say "I know I am being difficult" has found something more durable than passion.',
      ],
    },
  },

  /* ---------------- literature ---------------- */
  {
    id: 'common-reader',
    title: 'The Common Reader',
    authorId: 'virginia-woolf',
    authorName: 'Virginia Woolf',
    year: 1925,
    isbn: '9780156027786',
    category: 'Literature',
    axes: ['literature'],
    tags: ['Essays', 'Reading', 'Criticism'],
    palette: { bg: '#4A3A6B', fg: '#F3EFF9' },
    blurb: 'Essays on reading by someone who read for pleasure, wrote for a living, and thought the two should never be confused.',
    quote: {
      text: 'The only advice, indeed, that one person can give another about reading is to take no advice, to follow your own instincts, to use your own reason, to come to your own conclusions.',
      source: { work: 'The Common Reader: Second Series', loc: '"How Should One Read a Book?"', url: 'https://openlibrary.org/isbn/9780156027786' },
    },
    summary: {
      gist: 'Woolf takes her title from Dr Johnson’s "common reader" — the person who reads for pleasure rather than to instruct — and writes as one. The essays range across Chaucer, the Greeks, Defoe, Austen and the Brontës, and end with the question of how one should read at all.',
      ideas: [
        'Take no advice about reading; follow your own instincts.',
        'Read as the writer’s accomplice, not their judge — try to write a paragraph yourself.',
        'Two parts of reading: receiving impressions with an open mind, then judging.',
        'The reader’s pleasure and the reader’s judgement are both part of the work.',
        'Heaven, for readers, may simply be more reading.',
      ],
    },
    start: { label: 'Second Series', title: 'How Should One Read a Book?', why: 'The essay that refuses to tell you how to read, and in refusing tells you more than any method could.' },
    text: {
      kind: 'guide',
      heading: 'How Should One Read a Book?',
      note: GUIDE_NOTE,
      paragraphs: [
        'Woolf opens by noting the question mark in her title: she can only say how she reads, not how one should, and the only advice one person can give another is to take no advice. Reading, she insists, is the one activity where freedom is the point, and a reader who has been told what to think has been robbed of the pleasure that makes reading worth doing.',
        'The essay then describes two movements. The first is receptive: to read a novel is to try to be the novelist’s accomplice, to take in impressions before judging them, to let the book be what it is. She suggests trying to write a page of the thing yourself, to learn how hard it is. The second movement is judgement — comparison, evaluation, the placing of the book against others — which can only come after the first is complete.',
        'She ends with a scene that has become famous: on the Day of Judgement, the Almighty turns to Peter, seeing the readers arrive with their books under their arms, and says: "Look, these need no reward. We have nothing to give them here. They have loved reading." For the council’s question about getting more from reading, Woolf’s answer is the most liberating and the least methodical: love it, and take no advice.',
      ],
    },
  },
  {
    id: 'lectures-on-literature',
    title: 'Lectures on Literature',
    authorId: 'vladimir-nabokov',
    authorName: 'Vladimir Nabokov',
    year: 1980,
    isbn: '9780156027755',
    category: 'Literature',
    axes: ['literature'],
    tags: ['Close reading', 'Detail', 'Rereading'],
    palette: { bg: '#6B2A3A', fg: '#FBEFF2' },
    blurb: 'Nabokov’s Cornell lectures on Austen, Dickens, Flaubert, Kafka, Joyce and Proust — a master class in reading with a lepidopterist’s attention.',
    quote: { text: 'Curiously enough, one cannot read a book: one can only reread it.', source: { work: 'Lectures on Literature', loc: '"Good Readers and Good Writers"', url: 'https://openlibrary.org/isbn/9780156027755' } },
    summary: {
      gist: 'For Nabokov, literature is not ideas or "identification" but detail — the specific, sensuous, structural detail that only a rereading can hold in view. A good reader has imagination, memory, a dictionary and some artistic sense; a good writer is an enchanter first, a storyteller and teacher second.',
      ideas: [
        'Fondle details: the divine details.',
        'A first reading is labour, not reading; only rereading can be reading.',
        'Do not identify with characters; identify with the author who made them.',
        'Literature was born the day a boy cried "wolf" and there was no wolf behind him.',
        'The spine tingles: art is felt between the shoulder blades.',
      ],
    },
    start: { label: 'Opening lecture', title: 'Good Readers and Good Writers', why: 'The lecture that lays out what a reader owes a book — and the famous quiz on what makes a good reader.' },
    text: {
      kind: 'guide',
      heading: 'Good Readers and Good Writers',
      note: GUIDE_NOTE,
      paragraphs: [
        'Nabokov begins with a quiz he once gave students: pick four of ten qualities that make a good reader. The list includes belonging to a book club, identifying with the hero, focusing on the social-economic angle, and — the correct four — having imagination, memory, a dictionary and some artistic sense. Most students, he notes with satisfaction, chose wrong.',
        'From there he makes the case for rereading. On a first pass the eye moves laboriously across the lines, left to right, and the physical work of it stands between us and the book; only on the second, third and fourth readings do we behave toward the book as we do toward a painting, taking it in whole. The good reader, he says, is the rereader.',
        'The lecture then turns to the writer as storyteller, teacher and enchanter, and insists that the enchanter is what matters. For the council’s question about reading more deeply, Nabokov offers the opposite of Woolf’s freedom: a discipline of attention, exacting and unsentimental, in which the reward is a tingle in the spine that no summary can produce.',
      ],
    },
  },
  {
    id: 'why-read-classics',
    title: 'Why Read the Classics?',
    authorId: 'italo-calvino',
    authorName: 'Italo Calvino',
    year: 1991,
    category: 'Literature',
    axes: ['literature'],
    tags: ['Classics', 'Essays', 'Rereading'],
    palette: { bg: '#2A5A5A', fg: '#EEF6F6' },
    blurb: 'Fourteen definitions of a classic, followed by essays on Homer, Ovid, Stendhal, Borges and others that show what the definitions mean.',
    quote: { text: 'A classic is a book that has never finished saying what it has to say.', source: { work: 'Why Read the Classics?', loc: 'definition 6' } },
    summary: {
      gist: 'Calvino’s title essay offers fourteen playful, cumulative definitions — a classic is a book people are "rereading" rather than reading; a book that exerts an influence when it hides in the memory; a book that has never finished saying what it has to say — and concludes that the reason to read them is that it is better than not reading them.',
      ideas: [
        'A classic is a book that has never finished saying what it has to say.',
        'Every rereading of a classic is as much a voyage of discovery as the first.',
        'A classic comes to us bearing the traces of all the readings before ours.',
        'Your classic is the one you cannot feel indifferent to, and which helps you define yourself in relation to it.',
        'Read the classics for love, never for duty or respect.',
      ],
    },
    start: { label: 'Title essay', title: 'Why Read the Classics?', why: 'The fourteen definitions. Read them and then make your own list — Calvino insists there is no other way.' },
    text: {
      kind: 'guide',
      heading: 'Why Read the Classics?',
      note: GUIDE_NOTE,
      paragraphs: [
        'Calvino starts with a small confession: the classics are usually the books one is "rereading", never "reading", because to admit not having read them is embarrassing. From this he builds outward, one definition at a time, each correcting the last. Classics are the books that exert a peculiar influence — they refuse to be eradicated from the mind. They are the books that, when reread, are as fresh as the first time; and the ones that, read for the first time late in life, feel like rereadings.',
        'By the middle of the essay the definitions turn personal. A classic is a book which has never exhausted all it has to say to its readers; a book that comes to us bearing the traces of readings before ours; and, most usefully for anyone building a library, "your" classic is the one you cannot feel indifferent to, which helps you define yourself in relation to it, and perhaps in opposition to it.',
        'He ends by refusing the question in his title. The only reason to read the classics, he says, is that it is better than not reading them — and if someone objects that they are not worth the trouble, one can only quote Cioran on Socrates, who was learning a tune on the flute as they prepared the hemlock: "What good will it do you?" "To know this tune before dying." For the council’s question, Calvino is the voice that makes reading a matter of love and of building a self, rather than of technique.',
      ],
    },
  },
  {
    id: 'how-to-read-a-book',
    title: 'How to Read a Book',
    authorId: 'mortimer-adler',
    authorName: 'Mortimer J. Adler',
    year: 1940,
    isbn: '9780671212094',
    category: 'Literature',
    axes: ['literature', 'career'],
    tags: ['Method', 'Levels of reading', 'Marginalia'],
    palette: { bg: '#4A4A3A', fg: '#F5F4EC' },
    blurb: 'The classic manual on reading as a skill with levels — elementary, inspectional, analytical and syntopical — and the rules for each.',
    quote: { text: 'In the case of good books, the point is not to see how many of them you can get through, but rather how many can get through to you.', source: { work: 'How to Read a Book', loc: 'ch. 3', url: 'https://openlibrary.org/isbn/9780671212094' } },
    summary: {
      gist: 'Adler treats reading as a craft most adults never finish learning. Inspect a book before reading it; read it analytically by asking what it is about, what it says, whether it is true and what of it; and read several books syntopically to see a subject whole. Mark the book; argue with it.',
      ideas: [
        'Four questions for any book: what is it about, what is being said, is it true, what of it?',
        'Inspectional reading — skimming with purpose — is a skill, not a cheat.',
        'Come to terms with the author: find the key words and what they mean here.',
        'Do not say you disagree until you can say you understand.',
        'Marking a book is an expression of your differences and agreements with the author.',
      ],
    },
    start: { label: 'Part One', title: 'Chapter 2 — The Levels of Reading', why: 'The chapter that names the four levels and lets you find which one you are stuck at. Most readers, Adler thinks, never leave the first.' },
    text: {
      kind: 'guide',
      heading: 'The Levels of Reading',
      note: GUIDE_NOTE,
      paragraphs: [
        'Adler distinguishes four levels, each including the ones below. Elementary reading is what school teaches: what does the sentence say. Inspectional reading is the art of skimming systematically — the table of contents, the preface, a few paragraphs, the last pages — to learn in an hour what kind of book this is and whether it deserves more. Analytical reading is thorough, complete, and asks the four questions. Syntopical reading places several books on a subject side by side and reads the subject rather than the books.',
        'He is blunt that most adults stall at the first level and mistake speed for skill. The remedy is not to read faster but to read at the level the book deserves — quickly for the disposable, slowly and argumentatively for the good.',
        'For the council’s question the chapter offers the most methodical answer: reading more deeply is a learnable sequence of habits, and the first of them is to stop treating every book the same way.',
      ],
    },
  },
  {
    id: 'how-to-read-and-why',
    title: 'How to Read and Why',
    authorId: 'harold-bloom',
    authorName: 'Harold Bloom',
    year: 2000,
    isbn: '9780684859071',
    category: 'Literature',
    axes: ['literature', 'philosophy'],
    tags: ['Criticism', 'The self', 'Shakespeare'],
    palette: { bg: '#5A3A3A', fg: '#F7EFEF' },
    blurb: 'Bloom on stories, poems, novels and plays, and on the only reason he thinks we read: to strengthen and enlarge a solitary self.',
    quote: {
      text: 'Ultimately we read — as Bacon, Johnson, and Emerson agree — in order to strengthen the self, and to learn its authentic interests.',
      source: { work: 'How to Read and Why', loc: 'Prologue', url: 'https://openlibrary.org/isbn/9780684859071' },
    },
    summary: {
      gist: 'Against reading for politics, comfort or self-improvement, Bloom argues for reading for the difficult pleasure of it, in solitude, to become more oneself. His principles: clear your mind of cant; do not try to improve your neighbour; a scholar is a candle that the love and desire of all men will light; read to recover the ironic.',
      ideas: [
        'Read to strengthen the self, not to improve society.',
        'Clear your mind of cant — the received opinions of the moment.',
        'One does not read to improve one’s neighbour.',
        'Irony is the mode the best literature teaches, and the one most in danger of being lost.',
        'Shakespeare invented much of what we take to be human.',
      ],
    },
    start: { label: 'Prologue', title: 'Why Read?', why: 'Bloom’s five principles for reading, stated with characteristic confidence. Argue with them.' },
    text: {
      kind: 'guide',
      heading: 'Prologue — Why Read?',
      note: GUIDE_NOTE,
      paragraphs: [
        'Bloom opens by saying that there is no single way to read well, but there is a reason to read: to find oneself in an authentic relation to the self and its interests, in solitude. Information is available everywhere; wisdom is not, and reading deeply is the only reliable way to it he knows.',
        'His principles follow. Clear your mind of cant, in Dr Johnson’s sense — the received phrases of the moment. Do not attempt to improve your neighbour by what you read; the self is the proper object. A scholar is a candle that the love and desire of all men will light, in Emerson’s line, meaning that reading is contagious only through pleasure. Recover the ironic, since irony is what protects us from the literal. And the final principle: read deeply, not to believe, not to accept, not to contradict, but to learn to share in that one nature that writes and reads.',
        'For the council’s question, Bloom supplies the stakes. Reading more deeply is not, on his account, a hobby improved; it is the enlargement of a self that will otherwise be shaped entirely by the noise around it.',
      ],
    },
  },
  {
    id: 'seven-nights',
    title: 'Seven Nights',
    authorId: 'jorge-luis-borges',
    authorName: 'Jorge Luis Borges',
    year: 1980,
    category: 'Literature',
    axes: ['literature', 'philosophy'],
    tags: ['Lectures', 'Blindness', 'The Thousand and One Nights'],
    palette: { bg: '#3A3A5A', fg: '#F0F0F8' },
    blurb: 'Seven lectures given from memory by a blind man on the Divine Comedy, nightmares, the Thousand and One Nights, Buddhism, poetry, the Kabbalah and blindness itself.',
    quote: { text: 'I have always imagined that Paradise will be a kind of library.', source: { work: 'Poem of the Gifts', loc: '(1960)' } },
    summary: {
      gist: 'Delivered in Buenos Aires in 1977 without notes — Borges had been blind for two decades — the lectures are a reader’s autobiography: what the great books gave him, and how blindness, which took reading away, gave him a different kind of reading in return.',
      ideas: [
        'Reading is a form of happiness; a book that bores you was written for someone else.',
        'The Thousand and One Nights is a book that never ends, and that is its glory.',
        'Poetry happens in the meeting of the poem and the reader.',
        'Blindness can be a gift: it returns you to memory, the oldest library.',
        'Every book is a mirror; what you find depends on who is looking.',
      ],
    },
    start: { label: 'Seventh night', title: 'Blindness', why: 'The lecture in which Borges explains how losing his sight changed his reading, and what a reader has that cannot be taken.' },
    text: {
      kind: 'guide',
      heading: 'Blindness',
      note: GUIDE_NOTE,
      paragraphs: [
        'Borges begins with the fact and refuses the pity. He was appointed director of the National Library in the same year he lost the ability to read — "God, who with such splendid irony granted me books and blindness at one touch" — and the lecture is about what he did with the irony. He learned Anglo-Saxon, because it could be studied by ear; he composed poems in his head; he discovered that memory is itself a library.',
        'The lecture is also a small history of blind writers — Homer, Milton, Joyce, Groussac — and an argument that blindness is a way of life, one of the many styles of living, and not the worst. Everything that happens to a writer, he says, is given as clay, to be made into something.',
        'For the council’s question about getting more from reading, Borges is the voice of gratitude. His answer is not a method but a reminder of what the ability to read is — and that a reader who has stored the best lines in memory keeps them when the books are gone.',
      ],
    },
  },

  /* ---------------- library extras (the poster's shelf) ---------------- */
  {
    id: 'sapiens',
    title: 'Sapiens',
    authorId: 'yuval-noah-harari',
    authorName: 'Yuval Noah Harari',
    year: 2011,
    isbn: '9780062316097',
    category: 'History',
    axes: ['philosophy', 'literature'],
    tags: ['Big history', 'Fictions', 'Cooperation'],
    palette: { bg: '#D9D3C4', fg: '#1A1A1A' },
    blurb: 'A history of the species in one volume: how shared fictions let strangers cooperate, and what that cost.',
    quote: { text: 'You could never convince a monkey to give you a banana by promising him limitless bananas after death in monkey heaven.', source: { work: 'Sapiens', loc: 'ch. 2', url: 'https://openlibrary.org/isbn/9780062316097' } },
    summary: {
      gist: 'Three revolutions — cognitive, agricultural, scientific — made Homo sapiens the dominant animal. Harari’s central claim is that our edge is the ability to believe in things that exist only in our shared imagination: money, nations, gods, corporations, human rights.',
      ideas: [
        'Large-scale cooperation depends on shared fictions.',
        'The agricultural revolution was history’s biggest fraud: more people, worse lives.',
        'Money is the most universal and efficient system of mutual trust ever devised.',
        'Empires, religions and money unified the world.',
        'We are more powerful than ever and no happier.',
      ],
    },
    start: { label: 'Chapter 2', title: 'The Tree of Knowledge', why: 'The chapter on the cognitive revolution, with the monkey-heaven argument that the rest of the book rests on.' },
    text: {
      kind: 'guide',
      heading: 'The Tree of Knowledge',
      note: GUIDE_NOTE,
      paragraphs: [
        'Harari asks what changed about seventy thousand years ago that let an unremarkable ape spread across the planet, and answers: language of a particular kind. Not just the ability to warn of a lion, which many animals have, but the ability to say "the lion is the guardian spirit of our tribe" — to talk about things that do not exist.',
        'The chapter argues that this capacity for fiction is what allowed cooperation beyond the roughly 150 individuals who can know each other personally. Two Catholics who have never met can go on crusade together because they believe the same story; two lawyers can work for a corporation that exists only on paper. Chimpanzees, however clever, cannot do this — hence the banana.',
        'It is a chapter to read with the rest of the library in mind: many of the things the council argues about — money, careers, love as an institution — are, on Harari’s account, exactly these kinds of stories.',
      ],
    },
  },
  {
    id: 'daily-stoic',
    title: 'The Daily Stoic',
    authorId: 'ryan-holiday',
    authorName: 'Ryan Holiday',
    year: 2016,
    isbn: '9780735211735',
    category: 'Philosophy',
    axes: ['philosophy'],
    tags: ['Stoicism', 'Daily practice', 'Meditations'],
    palette: { bg: '#1E1E1E', fg: '#F3EFE6' },
    blurb: 'A Stoic passage and a short reflection for every day of the year, arranged by month and theme.',
    summary: {
      gist: 'Three hundred and sixty-six entries, each a quotation from Marcus, Seneca, Epictetus or another Stoic, newly translated, with a paragraph of commentary. Organised by the three Stoic disciplines — perception, action, will — and by monthly themes such as clarity, passions, awareness and virtue.',
      ideas: [
        'A page a day is a practice, not a reading.',
        'Perception, action, will: the three disciplines, one per season.',
        'The Stoics wrote for themselves first — so should you.',
        'Clarity comes from asking what is in your control, every morning.',
        'Memento mori is a tool for prioritising, not a mood.',
      ],
    },
    start: { label: 'January', title: 'Clarity', why: 'The first month’s theme, and the natural place to begin: thirty-one short pages on seeing what is yours.' },
    text: {
      kind: 'guide',
      heading: 'January — Clarity',
      note: GUIDE_NOTE,
      paragraphs: [
        'January opens with Epictetus on control — the first thing to learn is what is up to us and what is not — and the month circles that single idea from thirty-one angles: education as freedom, the value of a clear mind, the cost of chasing things that were never ours, the importance of a plan for the day.',
        'The entries are deliberately short. Holiday’s method is a page a morning, read before the phone, followed by a minute of reflection; the commentary is there to translate a two-thousand-year-old line into the question you will actually face that day.',
        'It is a good companion book for anyone who found the council’s Stoics persuasive and wants a daily habit rather than another argument.',
      ],
    },
  },
];
