/* generated by scratchpad/portraits3.py from Wikimedia Commons metadata — see public/portraits/CREDITS.md */
const FILES: Record<string, string> = {
  'angela-duckworth': 'angela-duckworth.jpg',
  'aristotle': 'aristotle.jpg',
  'bell-hooks': 'bell-hooks.jpg',
  'benjamin-graham': 'benjamin-graham.jpg',
  'brene-brown': 'brene-brown.jpg',
  'carol-dweck': 'carol-dweck.jpg',
  'charlie-munger': 'charlie-munger.jpg',
  'cs-lewis': 'cs-lewis.jpg',
  'epicurus': 'epicurus.jpg',
  'erich-fromm': 'erich-fromm.jpg',
  'esther-perel': 'esther-perel.jpg',
  'hannah-arendt': 'hannah-arendt.jpg',
  'italo-calvino': 'italo-calvino.jpg',
  'james-clear': 'james-clear.jpg',
  'john-bogle': 'john-bogle.jpg',
  'jon-kabat-zinn': 'jon-kabat-zinn.jpg',
  'joseph-campbell': 'joseph-campbell.jpg',
  'leo-tolstoy': 'leo-tolstoy.jpg',
  'marcus-aurelius': 'marcus-aurelius.jpg',
  'mortimer-adler': 'mortimer-adler.jpg',
  'nassim-taleb': 'nassim-taleb.jpg',
  'naval-ravikant': 'naval-ravikant.jpg',
  'peter-attia': 'peter-attia.jpg',
  'rainer-maria-rilke': 'rainer-maria-rilke.jpg',
  'viktor-frankl': 'viktor-frankl.jpg',
  'virginia-woolf': 'virginia-woolf.jpg',
  'vladimir-nabokov': 'vladimir-nabokov.jpg',
  'warren-buffett': 'warren-buffett.jpg',
};

/* resolved against the deploy base so the app also works under a sub-path (e.g. /council/) */
export const PORTRAITS: Record<string, string> = Object.fromEntries(
  Object.entries(FILES).map(([id, file]) => [id, `${import.meta.env.BASE_URL}portraits/${file}`]),
);
